daily_problems/2024/0226/personal_submission/cf1547e_lengli*.cpp

lengli's submission for 20240226

lengli's submission for 20240226

---

daily_problems/2024/02/0228/personal_submission/cf1260c_lengli_star.cpp

20240228 lengli's submission for CF1260C

20240228 lengli's submission for CF1260C

---

daily_problems/2024/02/0228/personal_submission/cf1152d_lengli_star.cpp

20240228 lengli's submission for CF1152D

20240228 lengli's submission for CF1152D

---

daily_problems/2024/02/0228/personal_submission/cf1260c_dinghc.cpp

cf1260c_submission

---

daily_problems/2024/02/0229/personal_submission/cf1512g_lengli_star.cpp

20240229 lengli's submission for 1512G

20240229 lengli's submission for 1512G

---

daily_problems/2024/03/0301/personal_submission/cf687a_lengli_star.cpp

20240301 lengli's submission

---

daily_problems/2024/02/0229/personal_submission/G1512.java

G1512_test_.java

---

daily_problems/2024/03/0302/personal_submission/cf584b_lengli_star.cpp

20240302 lengli's submission for CF584B

20240302 lengli's submission for CF584B

---

daily_problems/2024/03/0302/personal_submission/cf1936c_lengli.cpp

20240302 lengli's submission for CF1936C

20240302 lengli's submission for CF1936C

---

daily_problems/2024/03/0304/personal_submission/cf1185c2_lengli_star.cpp

20240304 lengli's submission for CF1185C2

20240304 lengli's submission for CF1185C2

---

daily_problems/2024/03/0304/personal_submission/cf1898d_lengli_star.py

20240304 lengli's submission for CF1898D

20240304 lengli's submission for CF1898D

---

daily_problems/2024/03/0304/personal_submission/cf1898d_dinghc.cpp

cf1898d submission

---

daily_problems/2024/03/0305/personal_submission/cf1083a_lengli_star.cpp

20240305 lengli's submission for CF1083A

20240305 lengli's submission for CF1083A

---

daily_problems/2024/03/0305/personal_submission/cf1190d_lengli_star.cpp

20240305 lengli's submission for CF1190D

20240305 lengli's submission for CF1190D

---

daily_problems/2024/03/0306/personal_submission/cf1194d_lengli_star.cpp

20240306 lengli's submission for CF1194D

20240306 lengli's submission for CF1194D

---

daily_problems/2024/03/0306/personal_submission/cf621e_lengli_star.cpp

20240306 lengli's submission for CF621E

20240306 lengli's submission for CF621E

---

daily_problems/2024/03/0306/personal_submission/cf1194d_rememorio.go

20240306 rememorio's submission for CF1194D

---

daily_problems/2024/03/0307/personal_submission/cf453a_lengli_star.cpp

20240307 lengli's submission for CF453A

20240307 lengli's submission for CF453A

---

daily_problems/2024/03/0307/personal_submission/cf855e_lengli_star.py

20240307 lengli's submission for CF855E

20240307 lengli's submission for CF855E

---

daily_problems/2024/03/0307/personal_submission/cf885e_fatalerror.py

20240307 fatalerror's submission for CF855E

20240307 fatalerror's submission

---

.github/workflows/records.py
.github/workflows/website.yml
.github/workflows/website/index.html

全量重算的方法：删除 gh-pages 分支的 records.js，然后手动触发 github actions 一次即可。

Allow skipping date without problems in activity graph

---

daily_problems/2024/03/0308/personal_submission/cf1185d_lengli_star.cpp

20240308 lengli's submission for CF1185D

20240308 lengli's submission for CF1185D

---

daily_problems/2024/03/0308/personal_submission/cf895d_lengli_star.cpp

20240308 lengli's submission for CF895D

20240308 lengli's submission for CF895D

---

daily_problems/2024/03/0309/personal_submission/cf1025b_lengli_star.py

20240309 lengli's submission for CF1025B

20240309 lengli's submission for CF1025B

---

daily_problems/2024/03/0309/personal_submission/cf1231e_lengli_star.py

20240309 lengli's submission for CF1231E

20240309 lengli's submission for CF1231E

---

daily_problems/2024/03/0311/personal_submission/cf780b_lengli_star.cpp

20240311 lengli's submission for CF780B

20240311 lengli's submission for CF780B

---

daily_problems/2024/03/0311/personal_submission/cf576b_sheepstick.cpp

cf576b_sheepstick.cpp

---

daily_problems/2024/03/0312/personal_submission/cf1098a_lengli_star.cpp

20240312 lengli's submission for CF1098A

20240312 lengli's submission for CF1098A

---

daily_problems/2024/03/0312/personal_submission/cf1098a_sheepstick.cpp

cf1098a_sheepstick.cpp

---

daily_problems/2024/03/0312/personal_submission/cf226d_lengli.cpp

20240312 lengli's submission for CF226D

20240312 lengli's submission for CF226D

---

daily_problems/2024/03/0313/personal_submission/cf827a_lengli_star.cpp

20240313 lengli's submission for CF827A

20240313 lengli's submission for CF827A

---

daily_problems/2024/03/0313/personal_submission/cf166b_lengli.cpp

20240313 lengli's submission for CF166B

20240313 lengli's submission for CF166B

---

daily_problems/2024/03/0314/personal_submission/cf788a_lengli_star.cpp

20240314 lengli's submission for CF788A

20240314 lengli's submission for CF788A

---

daily_problems/2024/03/0315/personal_submission/cf660d_lengli_star.cpp

20240315 lengli's submission for CF660D

20240315 lengli's submission for CF660D

---

daily_problems/2024/03/0315/personal_submission/cf1076e_lengli_star.cpp

20240315 lengli's submission for CF1076E

20240315 lengli's submission for CF1076E

---

daily_problems/2024/03/0316/personal_submission/cf665d_lengli_star.cpp

20240316 lengli's submission for CF665D

20240316 lengli's submission for CF665D

---

daily_problems/2024/03/0316/personal_submission/cf263d_lengli.cpp

20240316 lengli's submission for CF263D

20240316 lengli's submission for CF263D

---

daily_problems/2024/03/0318/personal_submission/cf863d_lengli_star.cpp

20240318 lengli's submission for CF863D

20240318 lengli's submission for CF863D

---

daily_problems/2024/03/0318/personal_submission/cf772b_lengli.cpp

20240318 lengli's submission for CF772B

20240318 lengli's submission for CF772B

---

daily_problems/2024/03/0319/personal_submission/cf773a_lengli.cpp

20240319 lengli's submission for CF773A

20240319 lengli's submission for CF773A

---

daily_problems/2024/03/0319/personal_submission/cf1878f_lengli.cpp

20240319 lengli's submission for CF1878F

20240319 lengli's submission for CF1878F

---

daily_problems/2024/03/0320/personal_submission/cf375a_lengli.cpp

20240320 lengli's submission for CF375A

20240320 lengli's submission for CF375A

---

daily_problems/2024/03/0320/personal_submission/cf571b_lengli.cpp

20240320 lengli's submission for CF 571B

20240320 lengli's submission for CF 571B

---

daily_problems/2024/03/0321/personal_submission/cf913c_lengli.cpp

20240321 lengli's submission for CF913C

20240321 lengli's submission for CF913C

---

daily_problems/2024/03/0320/personal_submission/cf375a_wangggong.cpp

20240321 wangggong's submission for cf375a

---

daily_problems/2024/03/0321/personal_submission/cf491b_lengli.cpp

20240321 lengli's submission for CF491B

20240321 lengli's submission for CF491B

---

daily_problems/2024/03/0322/personal_submission/cf566f_lengli_star.cpp

20240322 lengli's submission for CF566F

20240322 lengli's submission for CF566F

---

daily_problems/2024/03/0322/personal_submission/cf1153e_lengli.cpp

20240322 lengli's submission for CF1153E

20240322 lengli's submission for CF1153E

---

daily_problems/2024/03/0322/personal_submission/cf566f_Override.java

20240322 Create cf566f_Override.java

---

daily_problems/2024/03/0323/personal_submission/cf908c_lengli_star.cpp

20240323 lengli's submission for CF908C

20240323 lengli's submission for CF908C

---

daily_problems/2024/03/0323/personal_submission/cf908c_Override.java

Override's submission for cf908c

20240323 Create cf908c_Override.java

---

daily_problems/2024/03/0323/personal_submission/cf1526e_lengli.cpp

20240323 lengli's submission for CF1526E

20240323 lengli's submission for CF1526E

---

daily_problems/2024/03/0325/personal_submission/cf986b_lengli_star.cpp

20240325 lengli's submission for CF986B

20240325 lengli's submission for CF986B

---

daily_problems/2024/03/0325/personal_submission/cf963a_lengli.cpp

20240325 lengli's submission for CF963A

20240325 lengli's submission for CF963A

---

daily_problems/2024/03/0325/personal_submission/cf963a_wangggong.cpp
daily_problems/2024/03/0325/personal_submission/cf986b_wangggong.cpp

wangggong's submission 0325

---

daily_problems/2024/03/0325/personal_submission/cf986b_Override.java

Override's submission for cf986b

20240325 Create cf986b_Override.java

---

daily_problems/2024/03/0326/personal_submission/cf1413d_lengli.cpp

20240326 lengli's submission for CF1413D

20240326 lengli's submission for CF1413D

---

daily_problems/2024/03/0326/personal_submission/cf1012b_lengli.cpp

20240326 lengli's submission for CF1012B

20240326 lengli's submission for CF1012B

---

daily_problems/2024/03/0326/personal_submission/cf1413d_Override.java

Override's submission for cf1413d

20240326 Create cf1413d_Override.java

---

daily_problems/2024/03/0327/personal_submission/cf924b_lengli.cpp

20240327 lengli's submission for CF924B

20240327 lengli's submission for CF924B

---

daily_problems/2024/03/0327/personal_submission/cf1142b_lengli_star.cpp

20240327 lengli's submission for CF1142B

20240327 lengli's submission for CF1142B

---

daily_problems/2024/03/0327/personal_submission/cf924b_Override.java

20240327 Create cf924b_Override.java

---

daily_problems/2024/03/0328/personal_submission/cf891a_lengli.cpp

20240328 lengli's submission for CF891A

20240328 lengli's submission for CF891A

---

daily_problems/2024/03/0328/personal_submission/cf1163d_lengli.cpp

20240328 lengli's submission for CF1163D

20240328 lengli's submission for CF1163D

---

daily_problems/2024/03/0329/personal_submission/cf1045i_lengli.py

20240329 lengli's submission for CF1045I

20240329 lengli's submission for CF1045I

---

daily_problems/2024/03/0329/personal_submission/cf743e_lengli.cpp

20240329 lengli's submission for CF743E

20240329 lengli's submission for CF743E

---

daily_problems/2024/03/0330/personal_submission/cf1027d_lengli.cpp

20240330 lengli's submission for CF1027D

20240330 lengli's submission for CF1027D

---

daily_problems/2024/03/0330/personal_submission/cf744c_lengli.cpp

20240330 lengli's submission for CF744C

20240330 lengli's submission for CF744C

---

daily_problems/2024/04/0401/personal_submission/cf1016d_lengli_star.cpp

20240401 lengli's submission for CF1016D

20240401 lengli's submission for CF1016D

---

daily_problems/2024/04/0402/personal_submission/cf1148d_lengli_star.cpp

20240402 lengli's submission for CF1148D

20240402 lengli's submission for CF1148D

---

daily_problems/2024/04/0402/personal_submission/cf739b_lengli_star.cpp

20240402 lengli's submission for CF739B

20240402 lengli's submission for CF739B

---

daily_problems/2024/04/0402/personal_submission/cf1148d_wangggong.cpp
daily_problems/2024/04/0402/personal_submission/cf739b_wangggong.cpp

t2 属实不会, 直到最后都感觉复杂度爆炸 [Facepalm]

feat: wangggong 0402 submission

---

daily_problems/2024/04/0403/personal_submission/cf457a_lengli.cpp

20240403 lengli's submission for CF457A

20240403 lengli's submission for CF457A

---

daily_problems/2024/04/0403/personal_submission/cf870d_lengli.cpp

20240403 lengli's submission for CF870D

20240403 lengli's submission for CF870D

---

daily_problems/2024/04/0404/personal_submission/cf1468f_lengli.cpp

20240404 lengli's submission for CF1468F

20240404 lengli's submission for CF1468F

---

daily_problems/2024/04/0404/personal_submission/cf852b_lengli.cpp

20240404 lengli's submission for CF852B

20240404 lengli's submission for CF852B

---

daily_problems/2024/04/0401/personal_submission/cf1220d_lengli.cpp

20240401 lengli's submission for CF1220D

20240401 lengli's submission for CF1220D

---

daily_problems/2024/04/0405/personal_submission/cf1158c_lengli.cpp

20240405 lengli's submission for CF1158C

20240405 lengli's submission for CF1158C

---

daily_problems/2024/04/0406/personal_submission/cf946e_lengli.cpp

20240406 lengli's submission for CF946E

20240406 lengli's submission for CF946E

---

daily_problems/2024/04/0406/personal_submission/cf822c_lengli.cpp

20240406 lengli's submission for CF822C

20240406 lengli's submission for CF822C

---

daily_problems/2024/04/0406/personal_submission/cf822c_anonymous.py

20240406 Create cf822c_anonymous.py

---

daily_problems/2024/04/0408/personal_submission/cf492d_lengli.cpp

20240408 lengli's submission for CF492D

20240408 lengli's submission for CF492D

---

daily_problems/2024/04/0408/personal_submission/cf226b_lengli.cpp

20240408 lengli's submission for CF226B

20240408 lengli's submission for CF226B

---

daily_problems/2024/04/0408/personal_submission/cf492d_yskm-an.py

2024.04.08 yskm-an's submission

2024.04.08 yskm-an's submission

---

daily_problems/2024/04/0409/personal_submission/cf301a_lengli.cpp

20240409 lengli's submission for CF301A

20240409 lengli's submission for CF301A

---

daily_problems/2024/04/0409/personal_submission/cf613b_lengli.cpp

20240409 lengli's submission for CF613B

20240409 lengli's submission for CF613B

---

daily_problems/2024/04/0410/personal_submission/cf1102f_lengli.cpp

20240410 lengli's submission for CF1102F

20240410 lengli's submission for CF1102F

---

daily_problems/2024/04/0410/personal_submission/cf439d_ggl.py

202404010 Create cf439d_ggl.py

---

daily_problems/2024/04/0411/personal_submission/cf1903e_lengli.cpp

20240411 lengli's submission for CF1903E

20240411 lengli's submission for CF1903E

---

daily_problems/2024/04/0411/personal_submission/cf1592c_lengli.cpp

20240411 lengli's submission for CF1592C

20240411 lengli's submission for CF1592C

---

daily_problems/2024/04/0412/personal_submission/cf916c_lengli.cpp

20240412 lengli's submission for CF916C

20240412 lengli's submission for CF916C

---

daily_problems/2024/04/0412/personal_submission/cf540e_lengli.cpp

20240412 lengli's submssion for CF540E

20240412 lengli's submssion for CF540E

---

daily_problems/2024/04/0413/personal_submission/cf830b_lengli.cpp

20240413 lengli's submission for CF830B

20240413 lengli's submission for CF830B

---

daily_problems/2024/04/0413/cf1201d_lengli.cpp

20240413 lengli's submssion for CF1201D

20240413 lengli's submssion for CF1201D

---

daily_problems/2024/04/0415/personal_submission/cf933a_lengli.cpp

20240415 lengli's submission for CF933A

20240415 lengli's submission for CF933A

---

daily_problems/2024/04/0415/personal_submission/cf1912a_lengli.cpp

20240415 lengli's submission for CF1912A

20240415 lengli's submission for CF1912A

---

daily_problems/2024/04/0416/personal_submission/cf623a_lengli.cpp

20240416 lengli's submission for CF623A

20240416 lengli's submission for CF623A

---

daily_problems/2024/04/0416/personal_submission/cf558c_lengli.cpp

20240416 lengli's submission for CF558C

20240416 lengli's submission for CF558C

---

daily_problems/2024/04/0416/personal_submission/cf623a_jy_xiaoying.cpp

20240416 jy_xiaoying's submission for cf623a

20240416 jy_xiaoying's submission for cf623a

---

daily_problems/2024/04/0417/personal_submission/cf1578h_lengli.cpp

20240417 lengli's submission for CF 1578H

20240417 lengli's submission for CF 1578H

---

daily_problems/2024/04/0417/personal_submission/cf863e_lengli.cpp

20240417 lengli's submission for CF863E

20240417 lengli's submission for CF863E

---

daily_problems/2024/04/0417/personal_submission/cf1578h_jy_xiaoying.cpp

20240417 jy_xiaoying's submission for cf1578h

20240417 jy_xiaoying's submission for cf1578h

---

daily_problems/2024/04/0418/personal_submission/cf1310a_lengli.cpp

20240418 lengli's submission for CF1310A

20240418 lengli's submission for CF1310A

---

daily_problems/2024/04/0418/personal_submission/cf1010d_lengli.cpp

20240418 lengli's submission for CF1010D

20240418 lengli's submission for CF1010D

---

daily_problems/2024/04/0418/personal_submission/cf1310a_jy_xiaoying.cpp

20240418 jy_xiaoying's submission for cf1310a

20240418 jy_xiaoying's submission for cf1310a

---

daily_problems/2024/04/0419/personal_submission/cf1878d_lengli.cpp

20240419 lengli's submission for CF1878D

20240419 lengli's submission for CF1878D

---

daily_problems/2024/04/0419/personal_submission/cf662b_lengli.cpp

20240419 lengli's submission for CF662B

20240419 lengli's submission for CF662B

---

daily_problems/2024/04/0420/personal_submission/cf1031c_lengli.cpp

20240420 lengli's submission for CF1031C

20240420 lengli's submission for CF1031C

---

daily_problems/2024/04/0420/personal_submission/cf1615d_lengli.cpp

20240420 lengli's submission for CF1615D

20240420 lengli's submission for CF1615D

---

daily_problems/2024/04/0422/personal_submission/cf645d_lengli.cpp

20240422 lengli's submission for CF645D

20240422 lengli's submission for CF645D

---

daily_problems/2024/04/0422/personal_submission/cf1200d_lengli.cpp

20240422 lengli's submission for CF1200D

20240422 lengli's submission for CF1200D

---

daily_problems/2024/04/0422/personal_submission/cf1200d_yoonsica.py
daily_problems/2024/04/0422/personal_submission/cf645d_yoonsica.py

20240422 yoonsica's submission for cf645d and cf1200d

20240422 yoonsica's submission

---

daily_problems/2024/04/0422/personal_submission/cf645d_smallboatc.java

20240422 smallboatc's submission for CF645D

20240422 smallboatc's submission for CF645D

---

daily_problems/2024/04/0423/personal_submission/cf922d_lengli.cpp

20240423 lengli's submission for CF922D

20240423 lengli's submission for CF922D

---

daily_problems/2024/04/0423/personal_submission/cf500d_lengli.cpp

20240423 lengli's submission for CF500D

20240423 lengli's submission for CF500D

---

daily_problems/2024/04/0423/personal_submission/cf922d_Ku.py

20240423 cf922d

---

daily_problems/2024/04/0424/personal_submission/cf765d_lengli.cpp

20240424 lengli's submission for CF765D

20240424 lengli's submission for CF765D

---

daily_problems/2024/04/0424/personal_submission/cf749d_lengli.cpp

20240424 lengli's submission for CF749D

20240424 lengli's submission for CF749D

---

daily_problems/2024/04/0424/personal_submission/cf765d_gh123.java

cf765d_gh123.java

---

daily_problems/2024/04/0425/personal_submission/cf1114c_lengli.cpp

20240425 lengli's submission for CF1114C

20240425 lengli's submission for CF1114C

---

daily_problems/2024/04/0425/personal_submission/cf526c_lengli.cpp

20240425 lengli's submission for CF526C

20240425 lengli's submission for CF526C

---

daily_problems/2024/04/0426/personal_submission/cf1029c_lengli.cpp

20240426 lengli's submission for CF1029C

20240426 lengli's submission for CF1029C

---

daily_problems/2024/04/0426/personal_submission/cf1525e_lengli.cpp

20240426 lengli's submission for CF1525E

20240426 lengli's submission for CF1525E

---

daily_problems/2024/04/0426/personal_submission/cf1029c_gh123.java

cf1029c_gh123.java

---

daily_problems/2024/04/0427/personal_submission/cf573b_lengli.cpp

20240427 lengli's submission for CF573B

20240427 lengli's submission for CF573B

---

daily_problems/2024/04/0427/personal_submission/cf573b_gh123.java

cf573b_gh123.java

---

daily_problems/2024/04/0427/personal_submission/cf567e_lengli.cpp

20240427 lengli's submission for CF567E

20240427 lengli's submission for CF567E

---

daily_problems/2024/04/0429/cf1267j_lengli.cpp

20240429 lengli's submission for CF1267J

20240429 lengli's submission for CF1267J

---

daily_problems/2024/04/0429/personal_submission/cf1270d_lengli.cpp

20240429 lengli's submission for CF1270D

20240429 lengli's submission for CF1270D

---

daily_problems/2024/04/0429/personal_submission/cf1267j_pandaomeng.py

20240429 pandaomeng's submission for cf1267j

---

daily_problems/2024/04/0429/personal_submission/cf1270d_lyxxyx.cpp

cf1270d_lyxxyx.cpp

---

daily_problems/2024/04/0430/personal_submission/cf747d_lengli.cpp

20240430 lengli's submission for CF747D

20240430 lengli's submission for CF747D

---

daily_problems/2024/04/0430/personal_submission/cf1817b_lengli.cpp

20240430 lengli's submission for CF1817B

20240430 lengli's submission for CF1817B

---

daily_problems/2024/04/0430/personal_submission/cf747d_gh123.java

cf747d_gh123.java

---

daily_problems/2024/04/0430/personal_submission/cf747d_ku.py

20240430 ku's submission for cf747d

20240430 cf747d

---

daily_problems/2024/05/0501/personal_submission/cf631c_lengli.cpp

20240501 lengli's submission for CF631C

20240501 lengli's submission for CF631C

---

daily_problems/2024/05/0501/personal_submission/cf386c_lengli.cpp

20240501 lengli's submission for CF386C

20240501 lengli's submission for CF386C

---

daily_problems/2024/05/0501/personal_submission/cf631c_gh123.java

cf631c_gh123.java

---

daily_problems/2024/04/0425/personal_submission/cf1114c_wangggong.cpp
daily_problems/2024/04/0430/personal_submission/cf747d_wangggong.cpp
daily_problems/2024/05/0501/personal_submission/cf631c_wangggong.cpp

feat: wangggong 0425, 0430, 0501 submissions

---

daily_problems/2024/05/0502/personal_submission/cf1168a_lengli.cpp

20240502 lengli's submission for CF1168A

20240502 lengli's submission for CF1168A

---

daily_problems/2024/05/0502/personal_submission/cf1168a_gh123.java

cf1168a_gh123.java

---

daily_problems/2024/05/0502/personal_submission/cf954e_lengli.cpp

20240502 lengli's submission for CF954E

20240502 lengli's submission for CF954E

---

daily_problems/2024/05/0503/personal_submission/cf1163b2_lengli.cpp

20240503 lengli's submission for CF1163B2

20240503 lengli's submission for CF1163B2

---

daily_problems/2024/05/0503/personal_submission/cf1146d_lengli.cpp

20240503 lengli's submission for CF1146D

20240503 lengli's submission for CF1146D

---

daily_problems/2024/05/0503/personal_submission/cf1163b2_jy_xiaoying.cpp

20240503 jy_xiaoying's submission for cf1163b2

20240503 jy_xiaoying's submission for cf1163b2

---

daily_problems/2024/05/0504/personal_submission/cf1175c_lengli.cpp

20240504 lengli's submission for CF1175C

20240504 lengli's submission for CF1175C

---

daily_problems/2024/05/0504/personal_submission/cf1575l_lengli.cpp

20240504 lengli's submission for CF1575L

20240504 lengli's submission for CF1575L

---

daily_problems/2024/05/0504/personal_submission/cf1175c_gh123.java

cf1175c_gh123.java

---

daily_problems/2024/05/0504/personal_submission/cf1175c_jy_xiaoying.cpp

20240504 jy_xiaoying's submission for cf1175c

20240504 jy_xiaoying's submission for cf1175c

---

daily_problems/2024/05/0506/personal_submission/cf989c_lengli.cpp

20240506 lengli's submission for CF989C

20240506 lengli's submission for CF989C

---

daily_problems/2024/05/0506/personal_submission/cf989c_jy_xiaoying.cpp

20240506 jy_xiaoying's submission for cf989c

20240506 jy_xiaoying's submission for cf989c

---

daily_problems/2024/05/0506/personal_submission/cf1569d_lengli.cpp

20240506 lengli's submission for CF1569D

20240506 lengli's submission for CF1569D

---

daily_problems/2024/02/0226/personal_submission/cf1547e_lyxxys.cpp

cf1547e_lyxxys.cpp

---

daily_problems/2024/05/0507/personal_submission/cf1129a2_lengli.cpp

20240507 lengli's submission for CF1129A2

20240507 lengli's submission for CF1129A2

---

daily_problems/2024/05/0507/personal_submission/cf1644e_lengli.cpp

20240507 lengli's submission for CF1644E

20240507 lengli's submission for CF1644E

---

daily_problems/2024/05/0507/personal_submission/cf1129a2_jy_xiaoying.cpp

2024-0507 jy_xiaoying's submission for cf1129a2

2024-0507 jy_xiaoying's submission for cf1129a2

---

daily_problems/2024/05/0507/personal_submission/cf1129a2_gh123.cpp

cf1129a2_gh123.cpp

---

daily_problems/2024/05/0507/personal_submission/cf1644e_lyxxys.cpp

cf1644e_lyxxys.cpp

---

daily_problems/2024/05/0508/personal_submission/cf1102e_lengli.cpp

20240508 lengli's submission for CF1102E

20240508 lengli's submission for CF1102E

---

daily_problems/2024/05/0508/personal_submission/cf1102e_gh123.java

cf1102e_gh123.java

---

daily_problems/2024/05/0508/personal_submission/cf721d_lengli.cpp

20240508 lengli's submission for CF721D

20240508 lengli's submission for CF721D

---

daily_problems/2024/05/0508/personal_submission/cf1102e_jy_xiaoying.cpp

20240508 jy_xiaoying's submission for cf1102e

20240508 jy_xiaoying's submission for cf1102e

---

daily_problems/2024/05/0509/personal_submission/cf1019a_lengli.cpp

20240509 lengli's submission for CF1019A

20240509 lengli's submission for CF1019A

---

daily_problems/2024/05/0509/personal_submission/cf1019a_gh123.java

cf1019a_gh123.java

---

daily_problems/2024/05/0509/personal_submission/cf720a_lengli.cpp

20240509 lengli's submission for CF720A

20240509 lengli's submission for CF720A

---

daily_problems/2024/05/0510/personal_submission/cf1609d_lengli.cpp

20240510 lengli's submission for CF1609D

20240510 lengli's submission for CF1609D

---

daily_problems/2024/05/0510/personal_submission/cf859d_lengli.cpp

20240510 lengli's submission for CF859D

20240510 lengli's submission for CF859D

---

daily_problems/2024/05/0510/personal_submission/cf1609d_jy_xiaoying.cpp

20240510 jy_xiaoying's submission for cf1609d

20240510 jy_xiaoying's submission for cf1609d

---

daily_problems/2024/05/0510/personal_submission/cf1609d_gh123.java

cf1609d_gh123.java

---

daily_problems/2024/05/0511/personal_submission/cf1028c_lengli.cpp

20240511 lengli's submission for CF1028C

20240511 lengli's submission for CF1028C

---

daily_problems/2024/05/0511/personal_submission/cf852f_lengli.cpp

20240511 lengli's submission for CF852F

20240511 lengli's submission for CF852F

---

daily_problems/2024/05/0511/personal_submission/cf1028c_jy_xiaoying.cpp

20240511 jy_xiaoying's submission for cf1028c

20240511 jy_xiaoying's submission for cf1028c

---

daily_problems/2024/05/0513/personal_submission/cf799c_lengli.cpp

20240513 lengli's submission for CF799C

20240513 lengli's submission for CF799C

---

daily_problems/2024/05/0513/personal_submission/cf1029d_lengli.cpp

20240513 lengli's submission for CF1029D

20240513 lengli's submission for CF1029D

---

daily_problems/2024/05/0514/personal_submission/cf965d_lengli.cpp

20240514 lengli's submission for CF965D

20240514 lengli's submission for CF965D

---

daily_problems/2024/05/0514/personal_submission/cf914c_lengli.cpp

20240514 lengli's submission for CF914C

20240514 lengli's submission for CF914C

---

daily_problems/2024/05/0514/personal_submission/cf914c_jy_xiaoying.cpp

20240514 jy_xiaoying's submission for cf914c

20240514 jy_xiaoying's submission for cf914c

---

daily_problems/2024/05/0513/personal_submission/cf799c_jy_xiaoying.cpp

20240513 jy_xiaoying's submission for cf799c

20240513 jy_xiaoying's submission for cf799c

---

daily_problems/2024/05/0515/personal_submission/cf954c_lengli.cpp

20240515 Create cf954c_lengli.cpp

20240515 Create cf954c_lengli.cpp

---

daily_problems/2024/05/0515/personal_submission/cf490e_lengli.cpp

20240515 Create cf490e_lengli.cpp

20240515 Create cf490e_lengli.cpp

---

daily_problems/2024/05/0515/personal_submission/cf954c_jy_xiaoying.cpp

20240515 jy_xiaoying's submission for cf954c

20240515 jy_xiaoying's submission for cf954c

---

daily_problems/2024/05/0516/personal_submission/cf960c_gh123.java

cf960c_gh123.java

---

daily_problems/2024/05/0516/personal_submission/cf960c_lengli.cpp

20240516 lengli's submission for CF960C

20240516 lengli's submission for CF960C

---

daily_problems/2024/05/0516/personal_submission/cf1219g_lengli.cpp

20240516 lengli's submission for CF1219G

20240516 lengli's submission for CF1219G

---

daily_problems/2024/05/0517/personal_submission/cf1025c_lengli.cpp

20240517 lengli's submission for CF1025C

20240517 lengli's submission for CF1025C

---

daily_problems/2024/05/0517/personal_submission/cf1025c_gh123.java

cf1025c_gh123.java

---

daily_problems/2024/05/0517/personal_submission/cf909d_lengli.cpp

20240517 lengli's submission for CF909D

20240517 lengli's submission for CF909D

---

daily_problems/2024/05/0516/personal_submission/cf960c_jy_xiaoying.cpp

20240516 jy_xiaoying's submission for cf960c

20240516 jy_xiaoying's submission for cf960c

---

daily_problems/2024/05/0518/personal_submission/cf1056d_gh123.java

cf1056d_gh123.java

---

daily_problems/2024/05/0518/personal_submission/cf1056d_lengli.cpp

20240518 lengli's submission for CF1056D

20240518 lengli's submission for CF1056D

---

daily_problems/2024/05/0518/personal_submission/cf1575h_lengli.cpp

20240518 lengli's submission for CF1575H

20240518 lengli's submission for CF1575H

---

daily_problems/2024/05/0518/personal_submission/cf1056d_jy_xiaoying.cpp

20240518 jy_xiaoying's submission for cf1056d

20240518 jy_xiaoying's submission for cf1056d

---

daily_problems/2024/05/0520/personal_submission/cf917a_lengli.cpp

20240520 lengli's submission for CF917A

20240520 lengli's submission for CF917A

---

daily_problems/2024/05/0520/personal_submission/cf917a_gh123.java

cf917a_gh123.java

---

daily_problems/2024/05/0520/personal_submission/cf335b_lengli.cpp

20240520 lengli's submission for CF335B

20240520 lengli's submission for CF335B

---

daily_problems/2024/05/0520/personal_submission/cf917a_jy_xiaoying.cpp

20240520 jy_xiaoying's submission for cf917a

20240520 jy_xiaoying's submission for cf917a

---

daily_problems/2024/05/0521/personal_submission/cf533e_lengli.cpp

20240521 lengli's submission for CF533E

20240521 lengli's submission for CF533E

---

daily_problems/2024/05/0521/personal_submission/cf420c_lengli.cpp

20240521 lengli's submission for CF420C

20240521 lengli's submission for CF420C

---

daily_problems/2024/05/0522/personal_submission/cf1132c_lengli.cpp

20240522 lengli's submission for CF1132C

20240522 lengli's submission for CF1132C

---

daily_problems/2024/05/0522/personal_submission/cf314c_lengli.cpp

20240522 lengli's submission for CF314C

20240522 lengli's submission for CF314C

---

daily_problems/2024/05/0523/personal_submission/cf900c_lengli.cpp

20240523 lengli's submission for CF900C

20240523 lengli's submission for CF900C

---

daily_problems/2024/05/0523/personal_submission/cf501d_lengli.cpp

20240523 lengli's submission for CF501D

20240523 lengli's submission for CF501D

---

daily_problems/2024/05/0524/personal_submission/cf1095d_lengli.cpp

20240524 Yawn Sean's submission for CF1095D

20240524 Yawn Sean's submission for CF1095D

---

daily_problems/2024/05/0524/personal_submission/cf301b_lengli.cpp

20240524 lengli's submission for CF301B

20240524 lengli's submission for CF301B

---

daily_problems/2024/05/0523/personal_submission/cf900c_gh123.java

cf900c_gh123.java

---

daily_problems/2024/05/0525/personal_submission/cf962d_gh123.java

cf962d_gh123.java

---

daily_problems/2024/05/0525/personal_submission/cf962d_lengli.cpp

20240525 lengli's submission for CF962D

20240525 lengli's submission for CF962D

---

daily_problems/2024/05/0525/personal_submission/cf894e_lengli.cpp

20240525 lengli's submission for CF894E

20240525 lengli's submission for CF894E

---

daily_problems/2024/05/0527/personal_submission/cf1954d_lengli.cpp

20240527 lengli's submission for CF1954D

20240527 lengli's submission for CF1954D

---

daily_problems/2024/05/0527/personal_submission/cf835d_lengli.cpp

20240527 lengli's submission for CF835D

20240527 lengli's submission for CF835D

---

daily_problems/2024/05/0528/personal_submission/cf869c_lengli.cpp

20240528 lengli's submission for CF869C

20240528 lengli's submission for CF869C

---

daily_problems/2024/05/0528/personal_submission/cf1168b_lengli.cpp

20240528 lengli's submission for CF1168B

20240528 lengli's submission for CF1168B

---

daily_problems/2024/05/0529/personal_submission/cf1148c_lengli.cpp

20240529 lengli's submission

---

daily_problems/2024/05/0529/personal_submission/cf1148c_gh123.java

cf1148c_gh123.java

---

daily_problems/2024/05/0530/personal_submission/cf1217c_lengli.cpp

20240530 lengli's submission for CF1217C

20240530 lengli's submission for CF1217C

---

daily_problems/2024/05/0530/personal_submission/cf1083b_lengli.cpp

20240530 lengli's submission for CF1083B

20240530 lengli's submission for CF1083B

---

daily_problems/2024/05/0531/personal_submission/cf1671d_lengli.cpp

20240531 lengli's submission for CF1671D

20240531 lengli's submission for CF1671D

---

daily_problems/2024/05/0531/personal_submission/cf960d_lengli.cpp

20240531 lengli's submission for CF960D

20240531 lengli's submission for CF960D

---

daily_problems/2024/05/0531/personal_submission/cf1671_gh123.java

cf1671_gh123.java

---

daily_problems/2024/06/0601/personal_submission/cf1498c_lengli.cpp

20240601 lengli's submission for CF1498C

20240601 lengli's submission for CF1498C

---

daily_problems/2024/06/0601/personal_submission/cf802k_lengli.cpp

20240601 lengli's submission for CF802K

20240601 lengli's submission for CF802K

---

daily_problems/2024/06/0603/personal_submission/cf802b_lengli.cpp

20240603 lengli's submission for CF802B

20240603 lengli's submission for CF802B

---

daily_problems/2024/06/0603/personal_submission/cf862c_lengli.cpp

20240603 lengli's submission for CF862C

20240603 lengli's submission for CF862C

---

daily_problems/2024/06/0604/personal_submission/cf1949i_lengli.cpp

20240604 lengli's submission for CF1949I

20240604 lengli's submission for CF1949I

---

daily_problems/2024/06/0604/personal_submission/cf1133f2_lengli.cpp

20240604 lengli's submission for CF1133F2

20240604 lengli's submission for CF1133F2

---

daily_problems/2024/06/0604/personal_submission/cf1949i_Eunoiay.cpp

```c++
#include <bits/stdc++.h>
using namespace std;
using i64 = long long;
int main() {
int n;
cin >> n;
vector<int> x(n), y(n), r(n);
cin >> x[i] >> y[i] >> r[i];
}
vector<vector<int>> adj(n);
for (int j = 0; j < i; ++j) {
i64 dx = x[i] - x[j];
i64 dy = y[i] - y[j];
i64 dis = r[i] + r[j];
if (dx * dx + dy * dy == dis * dis) {
adj[i].push_back(j);
adj[j].push_back(i);
}
}
}
vector<int> clr(n, -1);
bool flg = false;
if (~clr[i]) {
continue;
}
clr[i] = 0;
stack<int> stk;
int c[2] = {};
c[0] = 1;
stk.push(i);
bool f = true;
while (!stk.empty()) {
auto u = stk.top();
stk.pop();
for (auto v : adj[u]) {
if (clr[v] == -1) {
clr[v] = clr[u] ^ 1;
c[clr[v]] += 1; …
```

20240604 Eunoiay's submission for CF1949I

---

daily_problems/2024/06/0604/personal_submission/cf1133f2_Eunoiay.cpp

```c++
int main() {
int n, m, D;
cin >> n >> m >> D;
vector<pair<int, int>> edges(m);
vector<int> e;
for (auto &[u, v] : edges) {
cin >> u >> v;
--u, --v;
if (u == 0 || v == 0) {
e.push_back(max(u, v));
}
}
if (e.size() < D) {
cout << "NO\n";
return 0;
}
DSU dsu(n);
for (auto [u, v] : edges) {
if (u && v) {
dsu.merge(u, v);
}
}
vector<int> block(n);
int cnt = 0;
for (int i = 1; i < n; ++i) {
block[i] = dsu.find(i);
if (dsu.root(i)) {
cnt += 1;
}
}	
if (cnt > D) {
cout << "NO\n";
return 0;
}
dsu.init(n);
vector<int> vis(n);
int need = D - cnt;
vector<pair<int, int>> ans;
for (auto v : e) {
int i = block[v];
if (!vis[i] || --need >= 0) {
vis[i] = 1;
dsu.merge(0, v);
ans.emplace_back(1, v + 1);
}
}
for (auto [u, v] : edges) {
if (u && v && …
```

20240604 Eunoiay's submission for CF1133F2

---

daily_problems/2024/06/0605/personal_submission/cf1579e2_lengli.cpp

20240605 lengli's submission for CF1579E2

20240605 lengli's submission for CF1579E2

---

daily_problems/2024/06/0605/personal_submission/cf1209g1_lengli.cpp

20240605 lengli's submission for CF1209G1

20240605 lengli's submission for CF1209G1

---

daily_problems/2024/06/0605/personal_submission/cf1209g1_eunoiay.cpp

```c++
int main() {
int n, q;
cin >> n >> q;
vector<int> a(n);
cin >> a[i];
--a[i];
}
vector<int> lt(N, -1), rt(N, -1), cnt(N);
int x = a[i];
cnt[x] += 1;
if (lt[x] == -1) {
lt[x] = rt[x] = i;
} else {
rt[x] = i;
}
}
vector<tuple<int, int, int>> p;
for (int i = 0; i < N; ++i) {
if (cnt[i]) {
p.emplace_back(lt[i], rt[i], cnt[i]);
}
}
sort(p.begin(), p.end());
vector<pair<int, int>> seg;
int mx = 0;
int ans = 0;
for (auto [l, r, c] : p) {
if (seg.empty() || l > seg.back().second) {
if (!seg.empty()) {
auto [x, y] = seg.back();
ans += y - x + 1 - mx;
}
seg.emplace_back(l, r);
mx = c;
} else  {
seg.back().second = max(seg.back().second, r);
mx = max(mx, c);
}
}
auto [x, y] = seg.back(); …
```

20240605 Eunoiay's submission for CF1290G1

---

daily_problems/2024/06/0605/personal_submission/cf1579e2_eunoiay.cpp

```c++
void solve() {
int n;
cin >> n;
vector<int> a(n);
cin >> a[i];
}
auto o = a;
sort(o.begin(), o.end());
o.erase(unique(o.begin(), o.end()), o.end());	
auto find = [&](int x) {
return lower_bound(o.begin(), o.end(), x) - o.begin() + 1;
};
Fenwick<int> fen(o.size());
i64 ans = 0;
int k = find(a[i]);
int x = fen.query(k - 1);
int y = fen.rangeQuery(k + 1, o.size());
if (x < y) {
ans += x;
} else {
ans += y;
}
fen.modify(k, 1);
}
cout << ans << "\n";
}
```

20240605 Eunoiay's submission for CF1579E2

---

daily_problems/2024/06/0606/personal_submission/cf1561d1_lengli.cpp

20240606 lengli's submission for CF1561D1

20240606 lengli's submission for CF1561D1

---

daily_problems/2024/06/0606/personal_submission/cf1619g_lengli.cpp

20240606 lengli's submission for CF1619G

20240606 lengli's submission for CF1619G

---

daily_problems/2024/06/0606/personal_submission/cf1561d1_JinYuManTang.cpp

20240606 JinYuManTang's submission for cf1561d1

20240606 JinYuManTang's submission for cf1561d1

---

daily_problems/2024/06/0606/personal_submission/cf1561d1_eunoiay.cpp

```c++
int main() {
int n, m;
cin >> n >> m;
vector<int> f(n + 1);
f[1] = 1;
int sum = 1;
for (int i = 2; i <= n; ++i) {
f[i] = (f[i] + sum) % m;
for (int l = 2, r; l <= i; l = r + 1) {
r = i / (i / l);
f[i] += 1LL * (r - l + 1) * f[i / l] % m;
f[i] %= m;
}
sum = (sum + f[i]) % m;
}
cout << f[n] << "\n";
return 0;
}
```

20240606 Eunoiay's submission for CF1561D1

---

daily_problems/2024/06/0606/personal_submission/cf1619g_eunoiay.cpp

```c++
void solve() {
int n, k;
cin >> n >> k;
map<int, vector<pair<int, int>>> row, col;
vector<int> t(n);
int x, y;
cin >> x >> y >> t[i];		
row[x].emplace_back(y, i);
col[y].emplace_back(x, i);
}
DSU dsu(n);
for (auto &[_, vec] : row) {
sort(vec.begin(), vec.end());
for (int i = 0; i + 1 < (int)vec.size(); ++i) {
if (vec[i + 1].first - vec[i].first <= k){
dsu.merge(vec[i + 1].second, vec[i].second);
}
}
}
for (auto &[_, vec] : col) {
sort(vec.begin(), vec.end());
for (int i = 0; i + 1 < (int)vec.size(); ++i) {
if (vec[i + 1].first - vec[i].first <= k){
dsu.merge(vec[i + 1].second, vec[i].second);
}
}
}
vector<int> e(n, inf);
int p = dsu.find(i);
e[p] = min(e[p], t[i]);
}
sort(e.rbegin(), e.rend());
int cur = -1;
for (int i = …
```

20240606 Eunoiay's submission for CF1619G

---

daily_problems/2024/06/0607/personal_submission/cf1461d_lengli.cpp

20240607 lengli's submission for CF1461D

20240607 lengli's submission for CF1461D

---

daily_problems/2024/06/0607/personal_submission/cf551d_lengli.cpp

20240607 lengli's submission for CF551D

20240607 lengli's submission for CF551D

---

daily_problems/2024/06/0607/personal_submission/cf1461d_Eunoiay.cpp

```c++
void solve() {
int n, q;
cin >> n >> q;
vector<int> a(n);
cin >> a[i];
}
set<i64> S;
function<void(int, int)> dfs = [&](int l, int r) {
if (l > r) {
return;
}
int mx = 0, mn = 1e6;
i64 sum = 0;
for (int i = l; i <= r; ++i) {
mx = max(a[i], mx);
mn = min(a[i], mn);
sum += a[i];
}
S.insert(sum);
if (l == r) {
return;
}
int mid = (mx + mn) / 2;
vector<int> b, c;
for (int i = l; i <= r; ++i) {
if (a[i] <= mid) {
b.push_back(a[i]);
} else {
c.push_back(a[i]);
}
}
int x = b.size();
int y = c.size();
for (int i = l, j = 0; i <= r; ++i, ++j) {
if (j < x) {
a[i] = b[j];
} else {
a[i] = c[j - x];
}
}
bool same = true;
for (int i = l; i <= r; ++i) {
if (a[i] != mid) {
same = false;
break;
}
}
if (same) {
return;
}
dfs(l, l + x - 1);
dfs(l + x, r);
};	
dfs(0, n - …
```

20240607 Eunoiay's submission for CF1416D

---

daily_problems/2024/06/0608/personal_submission/cf1056b_lengli.cpp

20240608 lengli's submission for CF1056B

20240608 lengli's submission for CF1056B

---

daily_problems/2024/06/0608/personal_submission/cf1056b_gh123.java

cf1056b_gh123.java

---

daily_problems/2024/06/0608/personal_submission/cf1575k_lengli.cpp

20240608 lengli's submission for CF1575K

20240608 lengli's submission for CF1575K

---

daily_problems/2024/06/0610/personal_submission/cf1286b_lengli.cpp

20240610 lengli's submission for CF1286B

20240610 lengli's submission for CF1286B

---

daily_problems/2024/06/0611/personal_submission/cf725d_lengli.cpp

20240611 lengli's submission for CF725D

20240611 lengli's submission for CF725D

---

daily_problems/2024/06/0611/personal_submission/cf893d_lengli.cpp

20240611 lengli's submission for CF893D

20240611 lengli's submission for CF893D

---

daily_problems/2024/06/0611/personal_submission/cf725d_gh123.java

cf725d_gh123.java

---

daily_problems/2024/06/0612/personal_submission/cf1153c_lengli.cpp

20240612 lengli's submission for CF1153C

20240612 lengli's submission for CF1153C

---

daily_problems/2024/06/0612/personal_submission/cf1153c_gh123.java

cf1153c_gh123.java

---

daily_problems/2024/06/0612/personal_submission/cf666b_lengli.cpp

20240612 lengli's submission for CF666B

20240612 lengli's submission for CF666B

---

daily_problems/2024/06/0613/personal_submission/cf1292b_gh123.java

cf1292b_gh123.java

---

daily_problems/2024/06/0613/personal_submission/cf1292b_lengli.cpp

20240613 lengli's submission for CF1292B

20240613 lengli's submission for CF1292B

---

daily_problems/2024/06/0613/personal_submission/cf958c2_lengli.cpp

20240613 lengli's submission for CF958C2

20240613 lengli's submission for CF958C2

---

daily_problems/2024/06/0613/personal_submission/cf1292b_lyxxys.cpp

cf1292b_lyxxys.cpp

---

daily_problems/2024/06/0612/personal_submission/cf666b_md.cpp
daily_problems/2024/06/0613/personal_submission/cf1292b_md.cpp

Adds personal submission for 20240613 cf1292b
Adds personal submission for 20240612 cf666b

20240613 md's submission

---

daily_problems/2024/06/0614/personal_submission/cf1615c_lengli.cpp

20240614 lengli's submission for CF1615C

20240614 lengli's submission for CF1615C

---

daily_problems/2024/06/0614/personal_submission/cf1615c_gh123.java

cf1615c_gh123.java

---

daily_problems/2024/06/0614/personal_submission/cf992d_lengli.cpp

20240614 lengli's submission for CF992D

20240614 lengli's submission for CF992D

---

daily_problems/2024/06/0614/personal_submission/cf1615c_ggl.py

20240614 Create cf1615c_ggl.py

---

daily_problems/2024/06/0615/personal_submission/cf1282b2_gh123.java

cf1282b2_gh123.java

---

daily_problems/2024/06/0615/personal_submission/cf1282b2_lengli.cpp

20240615 lengli's submission for CF1282B2

20240615 lengli's submission for CF1282B2

---

daily_problems/2024/06/0615/personal_submission/cf811d_lengli.cpp

20240615 lengli's submission for CF811D

20240615 lengli's submission for CF811D

---

daily_problems/2024/06/0614/personal_submission/cf1615c_banfenhaochi.cpp

20240616 submissions of banfenhaochi

---

daily_problems/2024/03/0301/personal_submission/cf687a_md.cpp
daily_problems/2024/03/0302/personal_submission/cf584b_md.cpp
daily_problems/2024/06/0613/personal_submission/cf958c2_md.cpp
daily_problems/2024/06/0614/personal_submission/cf992d_md.cpp

Adds personal submission for cf687a on 20240301
Adds personal submission for cf584b on 20240303
Adds personal submission for cf958c2 on 20240613
Adds personal submission for cf992d on 20240614

20240616 md's submission

---

daily_problems/2024/06/0617/personal_submission/cf1249d2_lengli.cpp

20240617 lengli's submission for CF1249D2

20240617 lengli's submission for CF1249D2

---

daily_problems/2024/06/0617/personal_submission/cf535d_lengli.cpp

20240617 lengli's submission for CF535D

20240617 lengli's submission for CF535D

---

daily_problems/2024/06/0618/personal_submission/cf33b_gh123.java

cf33b_gh123.java

---

daily_problems/2024/06/0618/personal_submission/cf33b_lengli.cpp

20240618 lengli's submission

---

daily_problems/2024/06/0618/personal_submission/cf819b_sigma-yyf.cpp

add cf819b_sigma-yyf.cpp

---

daily_problems/2024/06/0619/personal_submission/cf1051d_lengli.cpp

20240619 lengli's submission

---

daily_problems/2024/06/0620/personal_submission/cf678d_lengli.cpp

20240620 lengli's submission

---

daily_problems/2024/06/0620/personal_submission/cf678d_Meikisisui.java

20240620 Create cf678d_Meikisisui.java

---

daily_problems/2024/06/0620/personal_submission/cf678d_alwaysCE.cpp

20240620 Create cf678d_alwaysCE.cpp

20240620 alwaysCE's submission for cf678d

---

daily_problems/2024/06/0621/personal_submission/cf1151d_sigma-yyf.cpp

add cf1151d_sigma-yyf.cpp

---

daily_problems/2024/06/0621/personal_submission/cf1151d_Meikisisui.java

20240621 Meikisisui's submission for CF1151D

20240621 Meikisisui's submission for CF1151D

---

daily_problems/2024/06/0621/personal_submission/cf1151d_eunoiay.cpp

```c++
#include <bits/stdc++.h>
using namespace std;
using i64 = long long;
int main() {
int n;
cin >> n;
vector<int> a(n), b(n);
cin >> a[i] >> b[i];
}
vector<int> o(n);
iota(o.begin(), o.end(), 0);
sort(o.begin(), o.end(), [&](int i, int j) {
return a[i] - b[i] < a[j] - b[j];
});
i64 ans = 0;
ans += 1LL * (a[o[i]] - b[o[i]]) * (n - 1 - i);
ans += 1LL * b[o[i]] * (n - 1);
}
cout << ans << "\n";
return 0;
}
```

20240621 Eunoiay's submission for CF1151D

---

daily_problems/2024/06/0621/personal_submission/cf1151d_lengli.cpp

20240621 lengli's submission

---

daily_problems/2024/06/0621/personal_submission/cf1151d_alwaysCE.cpp

20240621 Create cf1151d_alwaysCE.cpp

20240621 alwaysCE's submission

---

daily_problems/2024/06/0619/personal_submission/cf1051d_Meikisisui.java

20240621 Create cf1051d_Meikisisui.java

20240621 Create cf1051d_Meikisisui.java

---

daily_problems/2024/06/0622/personal_submission/cf1033c_lengli.cpp

20240622 lengli's submission

---

daily_problems/2024/06/0622/personal_submission/cf1033c_alwaysCE.cpp

20240622 Create cf1033c_alwaysCE.cpp

20240622 alwaysCE's submission

---

daily_problems/2024/06/0624/personal_submission/cf336c_lengli.cpp

20240624 lengli's submission

---

daily_problems/2024/06/0624/personal_submission/cf535c_lengli.cpp

 20240624 lengli's submission

---

daily_problems/2024/06/0624/personal_submission/cf336c_alwaysCE.cpp
daily_problems/2024/06/0624/personal_submission/cf535c_alwaysCE.cpp

20240624 alwaysCE's submission for cf535c and cf336c

20240624 alwaysCE's submission

---

daily_problems/2024/06/0624/personal_submission/cf535c_KaMtuo.cpp

20240624 KaMtuo's submission

---

daily_problems/2024/06/0625/personal_submission/cf863c_lengli.cpp

20240625 lengli's submission

---

daily_problems/2024/06/0625/personal_submission/cf863c_alwaysCE.cpp

20240625 Create cf863c_alwaysCE.cpp

20240625 alwaysCE's submission for cf863c

---

daily_problems/2024/06/0626/personal_submission/cf833a_lengli.cpp

20240626 lengli's submission

---

daily_problems/2024/06/0626/personal_submission/cf833a_gh123.java

cf833a_gh123.java

---

daily_problems/2024/06/0626/personal_submission/cf833a_alwaysCE.cpp

20240626 Create cf833a_alwaysCE.cpp

20240626 alwaysCE's submission 

---

daily_problems/2024/06/0626/personal_submission/cf833a_Meikisisui.java

20240626 Create cf833a_Meikisisui.java

20240626 Create cf833a_Meikisisui.java

---

daily_problems/2024/06/0622/personal_submission/cf1033c_Meikisisui.java

20240626 Create cf1033c_Meikisisui.java

20240626 Create cf1033c_Meikisisui.java

---

daily_problems/2024/06/0626/personal_submission/cf833a_KOD.py

20240626  cf833a_KOD.py

---

daily_problems/2024/06/0627/personal_submission/cf1085d_gh123.java

cf1085d_gh123.java

---

daily_problems/2024/06/0627/personal_submission/cf1085d_lengli.cpp

20240627 lengli's submission

---

daily_problems/2024/06/0627/personal_submission/cf1085d_alwaysCE.cpp
daily_problems/2024/06/0627/personal_submission/cf366d_alwaysCE.cpp

20240627 alwaysCE's submission

20240627 alwaysCE's submission

---

daily_problems/2024/06/0628/personal_submission/cf1321c_gh123.java

cf1321c_gh123.java

---

daily_problems/2024/06/0628/personal_submission/cf74c_lengli.cpp

20240628 lengli's submission

---

daily_problems/2024/06/0628/personal_submission/CF1321C_Meikisisui.java

20240626 Create CF1321C_Meikisisui.java

20240626 Create CF1321C_Meikisisui.java

---

daily_problems/2024/06/0628/personal_submission/cf1321c_alwaysCE.cpp

20240628 Create cf1321c_alwaysCE.cpp

20240628 alwaysCE's submission

---

daily_problems/2024/06/0629/personal_submission/cf1196d2_lengli.cpp

20240629 lengli's submission

---

daily_problems/2024/06/0629/personal_submission/cf1196d2_alwaysCE.cpp

20240629 Create cf1196d2_alwaysCE.cpp

20240629 alwaysCE's submission

---

daily_problems/2024/07/0701/personal_submission/cf476d_lengli.cpp

20240701 lengli's submission

---

daily_problems/2024/07/0701/personal_submission/cf1833g_eunoiay.cpp

```c++
void solve() {
int n;
cin >> n;
vector<vector<pair<int, int>>> adj(n);
for (int i = 1; i < n; ++i) {
int u, v;
cin >> u >> v;
--u, --v;
adj[u].emplace_back(v, i);
adj[v].emplace_back(u, i);
}
vector<int> ans;
auto dfs = [&](auto &&self, int u, int p) -> int {
int siz = 1;
for (auto [v, i] : adj[u]) {
if (v != p) {
int x = self(self, v, u);
if (x == -1) {
return -1;
}
if (x == 3) {
ans.push_back(i);
} else {
siz += x;
}
}
}
return siz <= 3 ? siz : -1;
};
if (dfs(dfs, 0, -1) != 3) {
cout << -1 << "\n";
return;
}
cout << ans.size() << "\n";
for (int i = 0; i < (int)ans.size(); ++i) {
cout << ans[i] << " \n"[i == (int)ans.size() - 1];
}
}
```

20240701 Eunoiay's submission for CF1833G

---

daily_problems/2024/07/0701/personal_submission/cf476d_eunoiay.cpp

```c++
int main() {
int n, k;
cin >> n >> k;
cout << k * (6 * n - 1) << "\n";
for (int j : {1, 2, 3, 5}) {
cout << (6 * i + j) * k << " ";
}
cout << "\n";
}
return 0;
}
```

20240701 Eunoiay's submission for CF476D

---

daily_problems/2024/07/0701/personal_submission/cf1833g_alwaysCE.cpp
daily_problems/2024/07/0701/personal_submission/cf476d_alwaysCE.cpp

20240701 alwaysCE's submission

20240701 alwaysCE's submission

---

daily_problems/2024/07/0702/personal_submission/cf1442b_lengli.cpp

20240702 lengli's submission

---

daily_problems/2024/07/0703/personal_submission/cf739a_lengli.cpp

20240703 lengli's submission

---

daily_problems/2024/07/0703/personal_submission/cf739a_gh123.java

cf739a_gh123.java

---

daily_problems/2024/07/0704/personal_submission/cf1672d_lengli.cpp

20240704 lengli's submission

---

daily_problems/2024/07/0704/personal_submission/cf1672d_alwaysCE.cpp

20240704 Create cf1672d_alwaysCE.cpp

20240704 alwaysCE's submission

---

daily_problems/2024/07/0705/personal_submission/cf103d_lengli.cpp

20240705 lengli's submission

---

daily_problems/2024/07/0705/personal_submission/cf570c_tiger2005.cpp

20240705 tiger2005 → CF570C✔

---

daily_problems/2024/07/0706/personal_submission/cf231c_lengli.cpp

20240706 lengli's submission

---

daily_problems/2024/07/0708/personal_submission/cf1195d2_lengli.cpp

20240708 lengli's submission

---

daily_problems/2024/07/0708/personal_submission/cf1195d2_Meikisisui.java

20240708 Create cf1195d2_Meikisisui.java

20240708 Create cf1195d2_Meikisisui.java

---

daily_problems/2024/07/0709/personal_submission/cf111b_lengli.cpp

20240709 lengli's submission

---

daily_problems/2024/07/0710/personal_submission/cf1060e_lengli.cpp

20240710 lengli's submission

---

daily_problems/2024/07/0710/personal_submission/cf1060e_lyxxys.cpp

cf1060e_lyxxys.cpp

---

daily_problems/2024/07/0711/personal_submission/cf1131f_lengli.cpp

20240711 lengli's submission

---

daily_problems/2024/07/0711/personal_submission/cf611d_lengli.cpp

20240711 Yawn Sean's submission

20240711 Yawn Sean's submission

---

daily_problems/2024/07/0711/personal_submission/cf1131f_Meikisisui.java

20240711 Create cf1131f_Meikisisui.java

20240711 Create cf1131f_Meikisisui.java

---

daily_problems/2024/07/0712/personal_submission/cf992b_Meikisisui.java

20240712 Create cf992b_Meikisisui.java

20240712 Create cf992b_Meikisisui.java

---

daily_problems/2024/07/0712/personal_submission/cf992b_lengli.cpp

20240712 lengli's submission

---

daily_problems/2024/07/0713/personal_submission/cf1059c_lengli.cpp

20240713 lengli's submission

---

daily_problems/2024/07/0715/personal_submission/cf671a_lengli.cpp

20240715 lengli's submission

---

daily_problems/2024/07/0716/personal_submission/cf442b_lengli.cpp

20240716 lengli's submission

---

daily_problems/2024/07/0716/personal_submission/cf442b_Meikisisui.java

20240716 Create cf442b_Meikisisui.java

20240716 Create cf442b_Meikisisui.java

---

daily_problems/2024/07/0717/personal_submission/cf1594d_lengli.cpp

20240717 lengli's submission

---

daily_problems/2024/07/0717/personal_submission/cf1594d_Meikisisui.java

20240717 Create cf1594d_Meikisisui.java

20240717 Create cf1594d_Meikisisui.java

---

daily_problems/2024/07/0718/personal_submission/cf622c_lengli.cpp

20240718 lengli's submission

---

daily_problems/2024/07/0719/personal_submission/cf190e_lyxxys.cpp

cf190e_lyxxys.cpp

---

daily_problems/2024/07/0718/personal_submission/cf156c_md.cpp
daily_problems/2024/07/0720/personal_submission/cf954d_md.cpp

20240720 md's submission

---

daily_problems/2024/07/0722/personal_submission/cf1119d_mono_4.cpp

20240722 mono_4'submission for CF1119D

---

daily_problems/2024/07/0723/personal_submission/cf351a_JinYuManTang.py

20240723 JinYuManTang's submission for cf351a

20240723 JinYuManTang's submission for cf351a

---

daily_problems/2024/07/0724/personal_submission/cf798c_Meikisisui.java

20240724 Create cf798c_Meikisisui.java

20240724 Create cf798c_Meikisisui.java

---

daily_problems/2024/07/0724/personal_submission/cf798c_gh123.java

cf798c_gh123.java

---

daily_problems/2024/07/0724/personal_submission/cf367c_jun.cpp
daily_problems/2024/07/0724/personal_submission/cf798c_jun.cpp

submission for CF798C
submission for CF367C

20240724 Jun's Submission

---

daily_problems/2024/07/0726/personal_submission/cf1660e_Meikisisui.java

20240726 Create cf1660e_Meikisisui.java

20240726 Create cf1660e_Meikisisui.java

---

daily_problems/2024/07/0727/personal_submission/cf814c_gh123.java

20240727 Create  cf814c_gh123.java

---

daily_problems/2024/07/0730/personal_submission/20240730_cf626d_Meikisisui.java

20240730 Create cf626d_Meikisisui.java

20240730 Create cf626d_Meikisisui.java

---

daily_problems/2024/07/0731/personal_submission/cf1041d_gh123.java

20240731 Create cf1041d_gh123.java

---

daily_problems/2024/07/0731/personal_submission/cf1041d_Meikisisui.java

20240731 Create cf1041d_Meikisisui.java

20240731 Create cf1041d_Meikisisui.java

---

daily_problems/2024/08/0801/personal_submission/cf1329b_Meikisisui.java

20240801 Create cf1329b_Meikisisui.java

20240801 Create cf1329b_Meikisisui.java

---

daily_problems/2024/08/0802/personal_submission/cf888d_gh123.java

20240802 Create cf888d_gh123.java

---

daily_problems/2024/08/0802/personal_submission/cf888b_Meikisisui.java

20240802 Create cf888b_Meikisisui.java

20240802 Create cf888b_Meikisisui.java

---

daily_problems/2024/08/0803/personal_submission/cf835c_gh123.java

20240803 Create cf835c_gh123.java

---

daily_problems/2024/08/0803/personal_submission/cf358f_zrnstnsr.cs
daily_problems/2024/08/0803/personal_submission/cf835c_zrnstnsr.cpp

Templates are all written in csharp and I'm too lazy to rewrite them in cpp.

20240803 submissions of ghj123h (cf: zrnstnsr)

---

daily_problems/2024/08/0806/personal_submission/cf1177b_Meikisisui.java

20240806 Create cf1177b_Meikisisui.java

20240806 Create cf1177b_Meikisisui.java

---

daily_problems/2024/08/0807/personal_submission/cf578b_Meikisisui.java

20240807 Create cf578b_Meikisisui.java

20240807 Create cf578b_Meikisisui.java

---

daily_problems/2024/08/0807/personal_submission/cf578b_gh123.java

20240807Create cf578b_gh123.java

---

daily_problems/2024/08/0808/personal_submission/cf729d_gh123.java

20240808 Create cf729d_gh123.java

---

daily_problems/2024/08/0808/personal_submission/cf729d_Meikisisui.java

20240808 Create cf729d_Meikisisui.java

20240808 Create cf729d_Meikisisui.java

---

daily_problems/2024/08/0809/personal_submission/cf476c_gh123.java

20240809 Create cf476c_gh123.java

---

daily_problems/2024/08/0809/personal_submission/cf476c_Meikisisui.java

20240809 Create cf476c_Meikisisui.java

20240809 Create cf476c_Meikisisui.java

---

daily_problems/2024/08/0809/personal_submission/cf575f_Meikisisui.java

20240809 Create cf575f_Meikisisui.java

20240809 Create cf575f_Meikisisui.java

---

daily_problems/2024/08/0809/personal_submission/cf476c_zrnstnsr.cpp
daily_problems/2024/08/0809/personal_submission/cf575f_zrnstnsr.cpp

https://codeforces.com/problemset/submission/575/275389503
https://codeforces.com/problemset/submission/476/275379706

20240809 submissions of zrnstnsr

---

daily_problems/2024/08/0810/personal_submission/cf731e_gh123.java

20240810 Create cf731e_gh123.java

---

daily_problems/2024/08/0810/personal_submission/cf731e_zrnstnsr.cpp
daily_problems/2024/08/0810/personal_submission/cf949a_zrnstnsr.cpp

https://codeforces.com/problemset/submission/949/275521776
https://codeforces.com/problemset/submission/731/275523665

20240810 submissions of zrnstnsr

---

daily_problems/2024/08/0812/personal_submission/cf1090d_Meikisisui.java

20240812 Create cf1090d_Meikisisui.java

20240812 Create cf1090d_Meikisisui.java

---

daily_problems/2024/08/0812/personal_submission/cf1090d_zrnstnsr.cpp
daily_problems/2024/08/0812/personal_submission/cf729d_zrnstnsr.cpp

https://codeforces.com/problemset/submission/1090/275989852
https://codeforces.com/problemset/submission/724/275995522

20240812 submissions of zrnstnsr

---

daily_problems/2024/08/0813/personal_submission/cf822d_Meikisisui.java

20240813 Create cf822d_Meikisisui.java

20240813 Create cf822d_Meikisisui.java

---

daily_problems/2024/08/0813/personal_submission/cf722d_Meikisisui.java

20240813 Create cf722d_Meikisisui.java

20240813 Create cf722d_Meikisisui.java

---

daily_problems/2024/08/0813/personal_submission/cf722d_zrnstnsr.cpp
daily_problems/2024/08/0813/personal_submission/cf822d_zrnstnsr.cpp

https://codeforces.com/problemset/submission/822/276053392
https://codeforces.com/problemset/submission/722/276076489

20240813 submissions of zrnstnsr

---

daily_problems/2024/08/0814/personal_submission/cf578a_Meikisisui.java

20240814 Create cf578a_Meikisisui.java

20240814 Create cf578a_Meikisisui.java

---

daily_problems/2024/08/0814/personal_submission/cf1092e_zrnstnsr.cpp
daily_problems/2024/08/0814/personal_submission/cf578a_zrnstnsr.cpp

https://codeforces.com/problemset/submission/578/276404459
https://codeforces.com/problemset/submission/1092/276422353

20240814 submissions of zrnstnsr

---

daily_problems/2024/08/0815/personal_submission/cf464a_Meikisisui.java

20240815 Create cf464a_Meikisisui.java

20240815 Create cf464a_Meikisisui.java

---

daily_problems/2024/08/0815/personal_submission/c862d_zrnstnr.cpp
daily_problems/2024/08/0815/personal_submission/cf464a_zrnstnsr.cpp

https://codeforces.com/problemset/submission/464/276509532
https://codeforces.com/problemset/submission/862/276516541

20240815 submissions of zrnstnsr

---

daily_problems/2024/08/0816/personal_submission/cf1252c_Meikisisui.java

20240816 Create cf1252c_Meikisisui.java

20240816 Create cf1252c_Meikisisui.java

---

daily_problems/2024/08/0817/personal_submission/cf993a_gh123.java

20240817 cf993a_gh123.java

---

daily_problems/2024/08/0817/personal_submission/cf993a_Meikisisui.java

20240817 Create cf993a_Meikisisui.java

20240817 Create cf993a_Meikisisui.java

---

daily_problems/2024/08/0817/personal_submission/cf1039c_zrnstnsr.cpp
daily_problems/2024/08/0817/personal_submission/cf993a_zrnstnsr.cpp

https://codeforces.com/contest/993/submission/277061015
https://codeforces.com/contest/1039/submission/277070809

20240817 submissions of zrnstnsr

---

daily_problems/2024/08/0819/personal_submission/cf827b_Meikisisui.java

20240819 Create cf827b_Meikisisui.java

20240819 Create cf827b_Meikisisui.java

---

daily_problems/2024/08/0819/personal_submission/cf622d_Meikisisui.java

20240819 Create cf622d_Meikisisui.java

20240819 Create cf622d_Meikisisui.java

---

daily_problems/2024/08/0820/personal_submission/cf1600e_Meikisisui.java

20240820 Create cf1600e_Meikisisui.java

20240820 Create cf1600e_Meikisisui.java

---

daily_problems/2024/08/0819/personal_submission/cf827b_sjw712.cpp

20240819 Create cf827b_sjw712.cpp

---

daily_problems/2024/08/0820/personal_submission/cf1076d_Meikisisui.java

20240820 Create cf1076d_Meikisisui.java

20240820 Create cf1076d_Meikisisui.java

---

daily_problems/2024/08/0820/personal_submission/cf1076d_zrnstnsr.cpp
daily_problems/2024/08/0820/personal_submission/cf1600e_zrnstnsr.cpp

https://codeforces.com/contest/1076/submission/277250038
https://codeforces.com/contest/1600/submission/277254041

20240820 submissions of zrnstnsr

---

daily_problems/2024/08/0821/personal_submission/cf1644d_Meikisisui.java

20240821 Create cf1644d_Meikisisui.java

20240821 Create cf1644d_Meikisisui.java

---

daily_problems/2024/08/0821/personal_submission/cf1644d_zrnstnsr.cpp
daily_problems/2024/08/0821/personal_submission/cf681d_zrnstnsr.cpp

https://codeforces.com/problemset/submission/1644/277486116
https://codeforces.com/problemset/submission/681/277495295

20240821 submissions of zrnstnsr

---

daily_problems/2024/08/0822/personal_submission/cf689c_Meikisisui.java

20240822 Create cf689c_Meikisisui.java

20240822 Create cf689c_Meikisisui.java

---

daily_problems/2024/08/0822/personal_submission/cf360b_zrnstnsr.cpp
daily_problems/2024/08/0822/personal_submission/cf689c_zrnstnsr.cpp

https://codeforces.com/problemset/submission/689/277625446
https://codeforces.com/problemset/submission/360/277633582

zrnstnsr 20240822

---

daily_problems/2024/08/0823/personal_submission/cf878a_Meikisisui.java

20240823 Create cf878a_Meikisisui.java

20240823 Create cf878a_Meikisisui.java

---

daily_problems/2024/08/0823/personal_submission/cf1184a2_zrnstnsr.cpp
daily_problems/2024/08/0823/personal_submission/cf878a_zrnstnsr.cpp

https://codeforces.com/problemset/submission/878/277757009
https://codeforces.com/problemset/submission/1184/277763107

20240823 zrnstnsr

---

daily_problems/2024/08/0824/personal_submission/cf849b_Meikisisui.java

20240824 Create cf849b_Meikisisui.java

20240824 Create cf849b_Meikisisui.java

---

daily_problems/2024/08/0824/personal_submission/cf431e_zrnstnsr.cpp
daily_problems/2024/08/0824/personal_submission/cf849b_zrnstnsr.cpp

https://codeforces.com/problemset/submission/849/277863927
https://codeforces.com/problemset/submission/431/277912693****

zrnstnsr 20240824

---

daily_problems/2024/08/0826/personal_submission/cf432c_Meikisisui.java

20240826 Create cf432c_Meikisisui.java

20240826 Create cf432c_Meikisisui.java

---

daily_problems/2024/08/0826/personal_submission/cf1147b_zrnstnsr.cpp
daily_problems/2024/08/0826/personal_submission/cf432c_zrnstnsr.cpp

https://codeforces.com/problemset/submission/432/278198122
https://codeforces.com/problemset/submission/1147/278202887

zrnstnsr 20240826

---

daily_problems/2024/08/0827/personal_submission/cf1237c2_zrnstnsr.cpp
daily_problems/2024/08/0827/personal_submission/cf1290b_zrnstnsr.cpp

https://codeforces.com/problemset/submission/1290/278416000
https://codeforces.com/problemset/submission/1237/278421264

20240827 zrnstnsr

---

daily_problems/2024/08/0828/personal_submission/cf1278c_gh123.java

20240828 cf1278c_gh123.java

---

daily_problems/2024/08/0828/personal_submission/cf1278c_Meikisisui.java

20240828 Create cf1278c_Meikisisui.java

20240828 Create cf1278c_Meikisisui.java

---

daily_problems/2024/08/0828/personal_submission/cf1019b_zrnstnsr.cpp
daily_problems/2024/08/0828/personal_submission/cf1278c_zrnstnsr.cpp

https://codeforces.com/problemset/submission/1278/278498735
https://codeforces.com/problemset/submission/1019/278514427

zrnstnsr 20240828

---

daily_problems/2024/08/0829/personal_submission/cf850a_Meikisisui.java

20240829 Create cf850a_Meikisisui.java

20240829 Create cf850a_Meikisisui.java

---

daily_problems/2024/08/0829/personal_submission/cf850a_stcnpc.cpp

20240829 for cf850a

---

daily_problems/2024/08/0829/personal_submission/cf248c_zrnstnsr.cpp
daily_problems/2024/08/0829/personal_submission/cf850a_zrnstnsr.cpp

https://codeforces.com/problemset/submission/850/278681022
https://codeforces.com/problemset/submission/248/278685511

zrnstnsr 20240829

---

daily_problems/2024/08/0830/personal_submission/cf1176f_Meikisisui.java

20240830 Create cf1176f_Meikisisui.java

20240830 Create cf1176f_Meikisisui.java

---

daily_problems/2024/08/0830/personal_submission/cf768b_gh123.java

20240830 cf768b_gh123.java

---

daily_problems/2024/08/0830/personal_submission/cf768b_zrnstnsr.cpp

too busy to write Q2
https://codeforces.com/problemset/submission/768/278768437

20240830 zrnstnsr

---

daily_problems/2024/08/0831/personal_submission/cf847b_gh123.java

20240831 cf847b_gh123.java

---

daily_problems/2024/08/0831/personal_submission/cf847b_Meikisisui.java

20240831 Create cf847b_Meikisisui.java

20240831 Create cf847b_Meikisisui.java

---

daily_problems/2024/08/0830/personal_submission/cf1176f_zrnstnsr.cpp
daily_problems/2024/08/0831/personal_submission/cf847b_zrnstnsr.cpp

https://codeforces.com/problemset/submission/1176/278897727
https://codeforces.com/problemset/submission/847/278899692

zrnstnsr 20240830 T2 + 20240831 T1

---

daily_problems/2024/09/0902/personal_submission/cf117b_Meikisisui.java

20240902 Create cf117b_Meikisisui.java

20240902 Create cf117b_Meikisisui.java

---

daily_problems/2024/09/0902/personal_submission/cf1055c_Meikisisui.java

20240902 Create cf1055c_Meikisisui.java

20240902 Create cf1055c_Meikisisui.java

---

daily_problems/2024/08/0826/personal_submission/cf1147b_dawnmagnet.rs
daily_problems/2024/08/0827/personal_submission/cf1237c2.dawnmagnet.rs
daily_problems/2024/08/0827/personal_submission/cf1290b_dawnmagnet.rs
daily_problems/2024/08/0828/personal_submission/cf1019b_dawnmagnet.rs
daily_problems/2024/08/0828/personal_submission/cf1278c_dawnmagnet.rs
daily_problems/2024/08/0829/personal_submission/cf248c_dawnmagnet.rs
daily_problems/2024/08/0829/personal_submission/cf850a_dawnmagnet.rs
daily_problems/2024/08/0830/personal_submission/cf1176f_dawnmanget.rs
daily_problems/2024/08/0830/personal_submission/cf768b_dawnmagnet.rs

✨ feat: add multiple new problem solutions in Rust
Introduce several new Rust solutions for various algorithmic problems. These implementations enhance the repository by providing solutions to specific challenges, improving the overall problem-solving capabilities of the codebase. Each file corresponds to a unique problem, showcasing different approaches and techniques in Rust.
- Added `cf1147b_dawnmagnet.rs` for factorization and edge distance calculations.
- Added `cf1237c2_dawnmagnet.rs` for processing 3D points and finding pairs based on specific conditions.
- Added `cf1290b_dawnmagnet.rs` for character frequency queries in a string.
- Added `cf1019b_dawnmagnet.rs` for binary search based on query results.
- Added `cf1278c_dawnmagnet.rs` for solving a problem with cumulative sums and …

✨ feat: add multiple new problem solutions in Rust

---

daily_problems/2024/09/0902/personal_submission/cf1055c_zrnstnsr.cpp
daily_problems/2024/09/0902/personal_submission/cf117b_zrnstnsr.cpp

https://codeforces.com/problemset/submission/117/279370590
https://codeforces.com/problemset/submission/1055/279372407

zrnstnsr 20240902

---

daily_problems/2024/09/0903/personal_submission/cf873d_Meikisisui.java

20240903 Create cf873d_Meikisisui.java

20240903 Create cf873d_Meikisisui.java

---

daily_problems/2024/09/0903/personal_submission/cf873d_liryc.py

https://codeforces.com/contest/873/submission/279425899

20240903_liryc

---

daily_problems/2024/09/0903/personal_submission/cf1031d_Meikisisui.java

20240903 Create cf1031d_Meikisisui.java

20240903 Create cf1031d_Meikisisui.java

---

daily_problems/2024/09/0904/personal_submission/cf449a_gh123.java

20240904 Create cf449a_gh123.java

---

daily_problems/2024/09/0904/personal_submission/cf449a_Meikisisui.java

20240904 Create cf449a_Meikisisui.java

20240904 Create cf449a_Meikisisui.java

---

daily_problems/2024/09/0904/personal_submission/cf494b_Meikisisui.java

20240904 Create cf494b_Meikisisui.java

20240904 Create cf494b_Meikisisui.java
