Yawn-Sean/Daily_CF_Problems

- daily_problems/2024/09/0905/personal_submission/cf769d_Meikisisui.java
20240905 Create cf769d_Meikisisui.java
> 20240905 Create cf769d_Meikisisui.java

- daily_problems/2024/09/0905/personal_submission/cf353d_Meikisisui.java
20240905 Create cf353d_Meikisisui.java
> 20240905 Create cf353d_Meikisisui.java

- daily_problems/2024/09/0905/personal_submission/cf769d_gh123.java
> 20240905 Create cf769d_gh123.java

- daily_problems/2024/09/0905/personal_submission/cf769d_Ku.py
20240905 Ku's submission for cf769D
> 20240905 Ku's submission for cf769D

- daily_problems/2024/09/0906/personal_submission/cf593b_Meikisisui.java
20240906 Create cf593b_Meikisisui.java
> 20240906 Create cf593b_Meikisisui.java

- daily_problems/2024/09/0906/personal_submission/cf593b_zrnstnsr.cpp
- daily_problems/2024/09/0906/personal_submission/cf838b_zrnstnsr.cpp
https://codeforces.com/problemset/submission/593/280036915
https://codeforces.com/problemset/submission/838/280120094
> zrnstnsr 20240906

- daily_problems/2024/09/0907/personal_submission/cf858d_gh123.java
> 20240907 Create cf858d_gh123.java

- daily_problems/2024/09/0907/personal_submission/cf858d_Meikisisui.java
20240907 Create cf858d_Meikisisui.java
> 20240907 Create cf858d_Meikisisui.java

- daily_problems/2024/09/0907/personal_submission/cf858d_zrnstnsr.cpp
- daily_problems/2024/09/0907/personal_submission/cf870e_zrnstnsr.cpp
https://codeforces.com/problemset/submission/858/280230251
https://codeforces.com/problemset/submission/870/280233934
> zrnstnsr 20240907

- daily_problems/2024/09/0909/personal_submission/cf551b_Meikisisui.java
20240909 Create cf551b_Meikisisui.java
> 20240909 Create cf551b_Meikisisui.java

- daily_problems/2024/09/0910/personal_submission/cf913d_Meikisisui.java
20240910 Create cf913d_Meikisisui.java
> 20240910 Create cf913d_Meikisisui.java

- daily_problems/2024/09/0911/personal_submission/cf644b_gh123.java
> 20240911 Create cf644b_gh123.java

- daily_problems/2024/09/0911/personal_submission/cf644b_Meikisisui.java
20240911 Create cf644b_Meikisisui.java
> 20240911 Create cf644b_Meikisisui.java

- daily_problems/2024/09/0911/personal_submission/cf314b_Meikisisui.java
20240911 Create cf314b_Meikisisui.java
> 20240911 Create cf314b_Meikisisui.java

- daily_problems/2024/09/0912/personal_submission/cf1267e_Meikisisui.java
20240912 Create cf1267e_Meikisisui.java
> 20240912 Create cf1267e_Meikisisui.java

- daily_problems/2024/09/0912/personal_submission/cf1267e_gh123.java
> 20240912 Create cf1267e_gh123.java

- daily_problems/2024/09/0912/personal_submission/cf1061d_zrnstnsr.cpp
- daily_problems/2024/09/0912/personal_submission/cf1267e_zrnstnsr.cpp
https://codeforces.com/problemset/submission/1267/280806832
https://codeforces.com/problemset/submission/1061/280808713
> zrnstnsr 20240912

- daily_problems/2024/09/0912/personal_submission/cf1061d_Meikisisui.java
20240912 Create cf1061d_Meikisisui.java
> 20240912 Create cf1061d_Meikisisui.java

- daily_problems/2024/09/0912/personal_submission/cf1627e_gaoeight.cpp
20240912 Gaoeight's submission for cf1627e
> 20240912 Gaoeight's submission for cf1627e

- daily_problems/2024/09/0913/personal_submission/cf735c_gh123.java
> 20240913 Create cf735c_gh123.java

- daily_problems/2024/09/0913/personal_submission/cf735c_Meikisisui.java
20240913 Create cf735c_Meikisisui.java
> 20240913 Create cf735c_Meikisisui.java

- daily_problems/2024/09/0913/personal_submission/cf336d_Meikisisui.java
20240913 Create cf336d_Meikisisui.java
> 20240913 Create cf336d_Meikisisui.java

- daily_problems/2024/09/0913/personal_submission/cf735c_zrnstnsr.cpp
https://codeforces.com/contest/735/submission/281009626
Touch fish one time ywwuyi, one straight touch fish one straight ywwuyi
> zrnstnsr 20240913

- daily_problems/2024/09/0914/personal_submission/cf682c_gh123.java
> 20240914 Create cf682c_gh123.java

- daily_problems/2024/09/0914/personal_submission/cf682c_Meikisisui.java
20240914 Create cf682c_Meikisisui.java
> 20240914 Create cf682c_Meikisisui.java

- daily_problems/2024/09/0916/personal_submission/cf641c_Meikisisui.java
20240916 Create cf641c_Meikisisui.java
> 20240916 Create cf641c_Meikisisui.java

- daily_problems/2024/09/0916/personal_submission/cf1063c_Meikisisui.java
20240916 Create cf1063c_Meikisisui.java
> 20240916 Create cf1063c_Meikisisui.java

- daily_problems/2024/09/0916/personal_submission/cf641c_yui.cpp
> 20240916 yui's submission for cf641c

- daily_problems/2024/09/0919/personal_submission/cf281b_gh123.java
> 20240919 Create cf281b_gh123.java

- daily_problems/2024/09/0919/personal_submission/cf309a_lyxxys.py
> 20240920_cf309a_lyxxys.py

- daily_problems/2024/09/0925/personal_submission/cf1210b_Meikisisui.java
20240925 Create cf1210b_Meikisisui.java
> 20240925 Create cf1210b_Meikisisui.java

- daily_problems/2024/09/0925/personal_submission/cf1210b_gh123.java
> 20240925 Create cf1210b_gh123.java

- daily_problems/2024/09/0925/personal_submission/cf761e_Meikisisui.java
20240925 Create cf761e_Meikisisui.java
> 20240925 Create cf761e_Meikisisui.java

- daily_problems/2024/09/0926/personal_submission/cf895b_Meikisisui.java
20240926 Create cf895b_Meikisisui.java
> 20240926 Create cf895b_Meikisisui.java

- daily_problems/2024/09/0927/personal_submission/cf416c_Meikisisui.java
20240927 Create cf416c_Meikisisui.java
> 20240927 Create cf416c_Meikisisui.java

- daily_problems/2024/09/0927/personal_submission/cf416c_gh123.java
> 20240927 Create cf416c_gh123.java

- daily_problems/2024/09/0927/personal_submission/cf900e_lyxxys.cpp
> 20240927_cf900e_lyxxys.cpp

- daily_problems/2024/09/0928/personal_submission/cf429b_gh123.java
> 20240928 Create cf429b_gh123.java

- daily_problems/2024/09/0928/personal_submission/cf429b_Meikisisui.java
20240928 Create cf429b_Meikisisui.java
> 20240928 Create cf429b_Meikisisui.java

- daily_problems/2024/09/0930/personal_submission/cf946d_Meikisisui.java
20240930 Create cf946d_Meikisisui.java
> 20240930 Create cf946d_Meikisisui.java

- daily_problems/2024/10/1002/personal_submission/cf990d_gh123.java
> 20241002 Create cf990d_gh123.java

- daily_problems/2024/10/1002/personal_submission/cf990d_Meikisisui.java
20241002 Create cf990d_Meikisisui.java
> 20241002 Create cf990d_Meikisisui.java

- daily_problems/2024/10/1003/personal_submission/cf1472e_gh123.java
> 20241003 Create cf1472e_gh123.java

- daily_problems/2024/10/1003/personal_submission/cf1472e_Meikisisui.java
20241003 Create cf1472e_Meikisisui.java
> 20241003 Create cf1472e_Meikisisui.java

- daily_problems/2024/10/1003/personal_submission/cf1131d_lianxuhanshu.cpp
20241003 cf1131d_lianxuhanshu.cpp
> 20241003 lianxuhanshu submission for CF1131D

- daily_problems/2024/10/1004/personal_submission/cf922c_gh123.java
> 20241004 Create cf922c_gh123.java

- daily_problems/2024/10/1004/personal_submission/cf922c_Meikisisui.java
20241004 Create cf922c_Meikisisui.java
> 20241004 Create cf922c_Meikisisui.java

- daily_problems/2024/10/1005/personal_submission/cf731c_gh123.java
> 20241005 Create cf731c_gh123.java

- daily_problems/2024/10/1005/personal_submission/cf731c_lovs_code_lx.cpp
20241005 lovs_code_lx‘s submission for CF731C
> cf731c_lovs_code_lx.cpp

- daily_problems/2024/10/1005/personal_submission/cf731c_Meikisisui.java
20241005 Create cf731c_Meikisisui.java
> 20241005 Create cf731c_Meikisisui.java

- daily_problems/2024/10/1007/personal_submission/cf352b_Meikisisui.java
20241007 Create cf352b_Meikisisui.java
> 20241007 Create cf352b_Meikisisui.java

- daily_problems/2024/10/1008/personal_submission/cf1227d2_Meikisisui.java
20241008 Create cf1227d2_Meikisisui.java
> 20241008 Create cf1227d2_Meikisisui.java

- daily_problems/2024/10/1010/personal_submission/cf756a_gh123.java
> 20241010 Create cf756a_gh123.java

- daily_problems/2024/10/1010/personal_submission/cf756a_Meikisisui.java
20241010 Create cf756a_Meikisisui.java
> 20241010 Create cf756a_Meikisisui.java

- daily_problems/2024/10/1011/personal_submission/cf847h_Meikisisui.java
20241011 Create cf847h_Meikisisui.java
> 20241011 Create cf847h_Meikisisui.java

- daily_problems/2024/10/1012/personal_submission/cf1082c_Ku.py
20241012 Ku's submission for cf1082c
> 20241012 Ku's submission for cf1082c

- daily_problems/2024/10/1014/personal_submission/cf257c_Meikisisui.java
20241014 Create cf257c_Meikisisui.java
> 20241014 Create cf257c_Meikisisui.java

- daily_problems/2024/10/1014/personal_submission/cf257c_qsmcgogo.cpp
> 20241014 qsmcgogo's submission for cf 257c

- daily_problems/2024/10/1015/personal_submission/cf743d_qsmcgogo.cpp
> 20241015 qsmcgogo's submission for cf 743d

- daily_problems/2024/10/1016/personal_submission/cf1118e_gh123.java
> 20241016 Create cf1118e_gh123.java

- daily_problems/2024/10/1016/personal_submission/cf1118e_qsmcgogo.cpp
> 20241016 qsmcgogo'submission for cf 1118e

- daily_problems/2024/10/1016/personal_submission/cf1118e_Meikisisui.java
20241016 Create cf1118e_Meikisisui.java
> 20241016 Create cf1118e_Meikisisui.java

- daily_problems/2024/10/1017/personal_submission/cf1009c_gh123.java
> 20241017 Create cf1009c_gh123.java

- daily_problems/2024/10/1017/personal_submission/cf1009c_Meikisisui.java
20241017 Create cf1009c_Meikisisui.java
> 20241017 Create cf1009c_Meikisisui.java

- daily_problems/2024/10/1017/personal_submission/cf1009c_qsmcgogo.cpp
> 20241017 qsmcgogo's submission for cf1009c

- daily_problems/2024/10/1018/personal_submission/cf424c_Meikisisui.java
20241018 Create cf424c_Meikisisui.java
> 20241018 Create cf424c_Meikisisui.java

- daily_problems/2024/10/1019/personal_submission/cf405c_gh123.java
> 20241019 Create cf405c_gh123.java

- daily_problems/2024/10/1019/personal_submission/cf405c_Meikisisui.java
20241019 Create cf405c_Meikisisui.java
> 20241019 Create cf405c_Meikisisui.java

- daily_problems/2024/10/1021/personal_submission/cf487a_Meikisisui.java
20241021 Create cf487a_Meikisisui.java
> 20241021 Create cf487a_Meikisisui.java

- daily_problems/2024/10/1021/personal_submission/cf811c_Meikisisui.java
20241021 Create cf811c_Meikisisui.java
> 20241021 Create cf811c_Meikisisui.java

- daily_problems/2024/10/1022/personal_submission/cf238b_Meikisisui.java
20241022 Create cf238b_Meikisisui.java
> 20241022 Create cf238b_Meikisisui.java

- daily_problems/2024/10/1023/personal_submission/cf818d_gh123.java
> 20241023 Create cf818d_gh123.java

- daily_problems/2024/10/1023/personal_submission/cf818d_Meikisisui.java
20241023 Create cf818d_Meikisisui.java
> 20241023 Create cf818d_Meikisisui.java

- daily_problems/2024/10/1024/personal_submission/cf305b_Meikisisui.java
20241024 Create cf305b_Meikisisui.java
> 20241024 Create cf305b_Meikisisui.java

- daily_problems/2024/10/1025/personal_submission/cf407b_gh123.java
> 20241025 Create cf407b_gh123.java

- daily_problems/2024/10/1025/personal_submission/cf305b_Meikisisui.java
20241025 Create cf305b_Meikisisui.java
> 20241025 Create cf305b_Meikisisui.java

- daily_problems/2024/10/1026/personal_submission/cf712c_gh123.java
> 20241026 Create cf712c_gh123.java

- daily_problems/2024/10/1026/personal_submission/cf712c_Meikisisui.java
20241026 Create cf712c_Meikisisui.java
> 20241026 Create cf712c_Meikisisui.java

- daily_problems/2024/10/1028/personal_submission/cf1043e_Sam_Jiang.py
20241028 Sam_Jiang's submission for CF1043e
> 20241028 Create cf1043e_Sam_Jiang.py

- daily_problems/2024/10/1028/personal_submission/cf1252h_Meikisisui.java
20241028 Create cf1252h_Meikisisui.java
> 20241028 Create cf1252h_Meikisisui.java

- daily_problems/2024/10/1029/personal_submission/cf358d_Meikisisui.java
20241029 Create cf358d_Meikisisui.java
> 20241029 Create cf358d_Meikisisui.java

- daily_problems/2024/10/1030/personal_submission/cf621c_Meikisisui.java
20241030 Create cf621c_Meikisisui.java
> 20241030 Create cf621c_Meikisisui.java

- daily_problems/2024/10/1030/personal_submission/cf621c_gh123.java
> 20241030 Create cf621c_gh123.java

- daily_problems/2024/10/1031/personal_submission/cf590a_Meikisisui.java
20241031 Create cf590a_Meikisisui.java
> 20241031 Create cf590a_Meikisisui.java

- daily_problems/2024/11/1101/personal_submission/cf992c_gh123.java
> 20241101 Create cf992c_gh123.java

- daily_problems/2024/11/1101/personal_submission/cf992c_Meikisisui.java
20241101 Create cf992c_Meikisisui.java
> 20241101 Create cf992c_Meikisisui.java

- daily_problems/2024/11/1102/personal_submission/cf1062c_gh123.java
> 20241102 Create cf1062c_gh123.java

- daily_problems/2024/11/1104/personal_submission/cf1016c_Meikisisui.java
20241104 Create cf1016c_Meikisisui.java
> 20241104 Create cf1016c_Meikisisui.java

- daily_problems/2024/11/1105/personal_submission/cf1067b_Meikisisui.java
20241105 Create cf1067b_Meikisisui.java
> 20241105 Create cf1067b_Meikisisui.java

- daily_problems/2024/11/1106/personal_submission/cf575d_gh123.java
> 20241106 Create cf575d_gh123.java

- daily_problems/2024/11/1106/personal_submission/cf575d_Meikisisui.java
20241106 Create cf575d_Meikisisui.java
> 20241106 Create cf575d_Meikisisui.java

- daily_problems/2024/11/1107/personal_submission/cf1254a_Meikisisui.java
20241107 Create cf1254a_Meikisisui.java
> 20241107 Create cf1254a_Meikisisui.java

- daily_problems/2024/11/1108/personal_submission/cf1027c_Meikisisui.java
20241108 Create cf1027c_Meikisisui.java
> 20241108 Create cf1027c_Meikisisui.java

- daily_problems/2024/11/1109/personal_submission/cf979c_Meikisisui.java
20241109 Create cf979c_Meikisisui.java
> 20241109 Create cf979c_Meikisisui.java

- daily_problems/2024/11/1109/personal_submission/cf979c_gh123.java
> 20241109 Create cf979c_gh123.java

- daily_problems/2024/11/1111/personal_submission/cf1280b_Meikisisui.java
20241111 Create cf1280b_Meikisisui.java
> 20241111 Create cf1280b_Meikisisui.java

- daily_problems/2024/11/1112/personal_submission/cf847e_Meikisisui.java
20241112 Create cf847e_Meikisisui.java
> 20241112 Create cf847e_Meikisisui.java

- daily_problems/2024/11/1114/personal_submission/cf1580a_Meikisisui.java
20241114 Create cf1580a_Meikisisui.java
> 20241114 Create cf1580a_Meikisisui.java

- daily_problems/2024/11/1115/personal_submission/cf353c_Meikisisui.java
20241115 Create cf353c_Meikisisui.java
> 20241115 Create cf353c_Meikisisui.java

- daily_problems/2024/11/1116/personal_submission/cf430a_Meikisisui.java
20241116 Create cf430a_Meikisisui.java
> 20241116 Create cf430a_Meikisisui.java

- daily_problems/2024/11/1119/personal_submission/cf201b_Meikisisui.java
20241119 Create cf201b_Meikisisui.java
> 20241119 Create cf201b_Meikisisui.java

- daily_problems/2024/11/1120/personal_submission/cf507c_Meikisisui.java
20241120 Create cf507c_Meikisisui.java
> 20241120 Create cf507c_Meikisisui.java

- daily_problems/2024/11/1120/personal_submission/cf137e_Meikisisui.java
20241120 Create cf137e_Meikisisui.java
> 20241120 Create cf137e_Meikisisui.java

- daily_problems/2024/11/1121/personal_submission/cf1068c_Meikisisui.java
20241121 Create cf1068c_Meikisisui.java
> 20241121 Create cf1068c_Meikisisui.java

- daily_problems/2024/11/1122/personal_submission/cf873c_Meikisisui.java
20241122 Create cf873c_Meikisisui.java
> 20241122 Create cf873c_Meikisisui.java

- daily_problems/2024/11/1123/personal_submission/cf441e_lyxxys.cpp
> 20241123_cf441e_lyxxys.cpp

- daily_problems/2024/11/1123/personal_submission/cf337c_Meikisisui.java
20241123 Create cf337c_Meikisisui.java
> 20241123 Create cf337c_Meikisisui.java

- daily_problems/2024/11/1125/personal_submission/cf700b_Meikisisui.java
20241125 Create cf700b_Meikisisui.java
> 20241125 Create cf700b_Meikisisui.java

- daily_problems/2024/11/1126/personal_submission/cf174c_Meikisisui.java
20241126 Create cf174c_Meikisisui.java
> 20241126 Create cf174c_Meikisisui.java

- daily_problems/2024/11/1127/personal_submission/cf288c_Meikisisui.java
20241127 Create cf288c_Meikisisui.java
> 20241127 Create cf288c_Meikisisui.java

- daily_problems/2024/11/1128/personal_submission/cf398b_lyxxys.cpp
> 20241128_cf398b_lyxxys.cpp

- daily_problems/2024/11/1128/personal_submission/cf398b_Meikisisui.java
20241128 Create cf398b_Meikisisui.java
> 20241128 Create cf398b_Meikisisui.java

- daily_problems/2024/11/1128/personal_submission/cf119c_lyxxys.cpp
> 20241128_cf119c_lyxxys.cpp

- daily_problems/2024/11/1129/personal_submission/cf364a_Meikisisui.java
20241129 Create cf364a_Meikisisui.java
> 20241129 Create cf364a_Meikisisui.java

- daily_problems/2024/11/1130/personal_submission/cf319a_gh123.java
> 1130 Create cf319a_gh123.java

- daily_problems/2024/11/1130/personal_submission/cf319a_Meikisisui.java
20241130 Create cf319a_Meikisisui.java
> 20241130 Create cf319a_Meikisisui.java

- daily_problems/2024/12/1202/personal_submission/cf396b_Meikisisui.java
20241202 Create cf396b_Meikisisui.java
> 20241202 Create cf396b_Meikisisui.java

- daily_problems/2024/12/1203/personal_submission/cf883h_Meikisisui.java
20241203 Create cf883h_Meikisisui.java
> 20241203 Create cf883h_Meikisisui.java

- daily_problems/2024/12/1204/personal_submission/cf297a_gh123.java
> 20241204 Create cf297a_gh123.java

- daily_problems/2024/12/1205/personal_submission/cf698b_gh123.java
> 20241205 Create cf698b_gh123.java

- daily_problems/2024/12/1205/personal_submission/cf698b_Meikisisui.java
20241205 Create cf698b_Meikisisui.java
> 20241205 Create cf698b_Meikisisui.java

- daily_problems/2024/12/1206/personal_submission/cf250c_Meikisisui.java
20241206 Create cf250c_Meikisisui.java
> 20241206 Create cf250c_Meikisisui.java

- daily_problems/2024/12/1206/personal_submission/cf209b_Meikisisui.java
20241206 Create cf209b_Meikisisui.java
> 20241206 Create cf209b_Meikisisui.java

- daily_problems/2024/12/1207/personal_submission/cf639c_lyxxys.cpp
> 20241207_cf639c_lyxxys.cpp

- daily_problems/2024/12/1207/personal_submission/cf1523c_Meikisisui.java
20241207 Create cf1523c_Meikisisui.java
> 20241207 Create cf1523c_Meikisisui.java

- daily_problems/2024/12/1209/personal_submission/cf185b_gh123.java
> 20241209 Create cf185b_gh123.java

- daily_problems/2024/12/1209/personal_submission/cf185b_Meikisisui.java
20241209 Create cf185b_Meikisisui.java
> 20241209 Create cf185b_Meikisisui.java

- daily_problems/2024/12/1209/personal_submission/cf356b_Meikisisui.java
20241209 Create cf356b_Meikisisui.java
> 20241209 Create cf356b_Meikisisui.java

- daily_problems/2024/12/1209/personal_submission/cf185b_lyxxys.cpp
> 20241209_cf185b_lyxxys.cpp

- daily_problems/2024/12/1211/personal_submission/cf1219c_Meikisisui.java
20241211 Create cf1219c_Meikisisui.java
> 20241211 Create cf1219c_Meikisisui.java

- daily_problems/2024/12/1210/personal_submission/cf257d_liryc.py
- daily_problems/2024/12/1211/personal_submission/cf671b_liryc.py
> 20241211_liryc

- daily_problems/2024/12/1211/personal_submission/cf671b_Meikisisui.java
20241211 Create cf671b_Meikisisui.java
> 20241211 Create cf671b_Meikisisui.java

- daily_problems/2024/12/1212/personal_submission/cf1142a_Meikisisui.java
20241212 Create cf1142a_Meikisisui.java
> 20241212 Create cf1142a_Meikisisui.java

- daily_problems/2024/12/1213/personal_submission/cf86a_gh123.java
> 20241213 Create cf86a_gh123.java

- daily_problems/2024/12/1213/personal_submission/cf86a_Meikisisui.java
20241213 Create cf86a_Meikisisui.java
> 20241213 Create cf86a_Meikisisui.java

- daily_problems/2024/12/1214/personal_submission/cf848a_Meikisisui.java
20241214 Create cf848a_Meikisisui.java
> 20241214 Create cf848a_Meikisisui.java

- daily_problems/2024/12/1214/personal_submission/cf848a_gh123.java
> 20241214 Create cf848a_gh123.java

- daily_problems/2024/12/1220/personal_submission/cf297b_Meikisisui.java
20241220 Create cf297b_Meikisisui.java
> 20241220 Create cf297b_Meikisisui.java

- daily_problems/2024/12/1220/personal_submission/cf297b_gh123.java
> 20241220 Create cf297b_gh123.java

- daily_problems/2024/12/1221/personal_submission/cf980b_gh123.java
> 20241221 Create cf980b_gh123.java

- daily_problems/2024/12/1221/personal_submission/cf980b_Meikisisui.java
20241221 Create cf980b_Meikisisui.java
> 20241221 Create cf980b_Meikisisui.java

- daily_problems/2024/12/1223/personal_submission/cf77b_Meikisisui.java
20241223 Create cf77b_Meikisisui.java
> 20241223 Create cf77b_Meikisisui.java

- daily_problems/2024/12/1223/personal_submission/cf134b_Meikisisui.java
20241223 Create cf134b_Meikisisui.java
> 20241223 Create cf134b_Meikisisui.java

- daily_problems/2024/12/1223/personal_submission/cf77b_gh123.java
> 20241223 Create cf77b_gh123.java

- daily_problems/2024/12/1224/personal_submission/cf142b_Meikisisui.java
20241224 Create cf142b_Meikisisui.java
> 20241224 Create cf142b_Meikisisui.java

- daily_problems/2024/12/1224/personal_submission/cf142b_gh123.java
> 20241224 Create cf142b_gh123.java

- daily_problems/2024/12/1226/personal_submission/cf1610d_lyxxys.cpp
> 20241226_cf1610d_lyxxys.cpp

- daily_problems/2024/12/1227/personal_submission/cf276e_lyxxys.cpp
> 20241227_cf276e_lyxxys.cpp

- daily_problems/2024/12/1228/personal_submission/cf306d_lyxxys.cpp
> 20241228_cf306d_lyxxys.cpp

- daily_problems/2024/12/1228/personal_submission/cf323a_Meikisisui.java
20241228 Create cf323a_Meikisisui.java
> 20241228 Create cf323a_Meikisisui.java

- daily_problems/2024/12/1231/personal_submission/cf1575d_Meikisisui.java
20241231 Create cf1575d_Meikisisui.java
> 20241231 Create cf1575d_Meikisisui.java

- daily_problems/2025/01/0102/personal_submission/cf581d_Meikisisui.java
20250102 Create cf581d_Meikisisui.java
> 20250102 Create cf581d_Meikisisui.java

- daily_problems/2025/01/0103/personal_submission/cf725c_Meikisisui.java
20250103 Create cf725c_Meikisisui.java
> 20250103 Create cf725c_Meikisisui.java

- daily_problems/2025/01/0103/personal_submission/cf725c_lyxxys.cpp
> 20250103_cf725c_lyxxys.cpp

- daily_problems/2025/01/0104/personal_submission/cf704a_Meikisisui.java
20250104 Create cf704a_Meikisisui.java
> 20250104 Create cf704a_Meikisisui.java

- daily_problems/2025/01/0107/personal_submission/cf846b_Meikisisui.java
20250107 Create cf846b_Meikisisui.java
> 20250107 Create cf846b_Meikisisui.java

- daily_problems/2025/01/0101/personal_submission/cf2045b_lyxxys.cpp
> 20250108_cf2045b_lyxxys.cpp

- daily_problems/2025/01/0108/personal_submission/cf43d_lyxxys.cpp
> 20250108_cf43d_lyxxys.cpp

- daily_problems/2025/01/0108/personal_submission/cf789b_Meikisisui.java
20250108 Create cf789b_Meikisisui.java
> 20250108 Create cf789b_Meikisisui.java

- daily_problems/2025/01/0110/personal_submission/cf240c_gh123.java
> 20250110 cf240c_gh123.java

- daily_problems/2025/01/0110/personal_submission/cf340c_Meikisisui.java
20250110 Create cf340c_Meikisisui.java
> 20250110 Create cf340c_Meikisisui.java

- daily_problems/2025/01/0111/personal_submission/cf231d_gh123.java
> 20250111 Create cf231d_gh123.java

- daily_problems/2025/01/0111/personal_submission/cf231d_Meikisisui.java
20250111 Create cf231d_Meikisisui.java
> 20250111 Create cf231d_Meikisisui.java

- daily_problems/2025/01/0113/personal_submission/cf1136d_Meikisisui.java
20250113 Create cf1136d_Meikisisui.java
> 20250113 Create cf1136d_Meikisisui.java

- daily_problems/2025/01/0114/personal_submission/cf733c_lyxxys.cpp
> 20250114_cf733c_lyxxys.cpp

- daily_problems/2025/02/0206/personal_submission/cf627b_Meikisisui.java
20250206 Create cf627b_Meikisisui.java
> 20250206 Create cf627b_Meikisisui.java

- daily_problems/2025/02/0207/personal_submission/cf1017c_Meikisisui.java
20250207 Create cf1017c_Meikisisui.java
> 20250207 Create cf1017c_Meikisisui.java

- daily_problems/2025/02/0208/personal_submission/cf1452d_Meikisisui.java
20250208 Create cf1452d_Meikisisui.java
> 20250208 Create cf1452d_Meikisisui.java

- daily_problems/2025/02/0208/personal_submission/cf1452d_gh123.java
> 20250208 cf1452d_gh123.java

- daily_problems/2025/02/0210/personal_submission/cf1082d_Meikisisui.java
20250210 Create cf1082d_Meikisisui.java
> 20250210 Create cf1082d_Meikisisui.java

- daily_problems/2025/02/0211/personal_submission/cf979b_Meikisisui.java
20250211 Create cf979b_Meikisisui.java
> 20250211 Create cf979b_Meikisisui.java

- daily_problems/2025/02/0212/personal_submission/cf518d_Meikisisui.java
20250212 Create cf518d_Meikisisui.java
> 20250212 Create cf518d_Meikisisui.java

- daily_problems/2025/02/0213/personal_submission/cf729c_Meikisisui.java
20250213 Create cf729c_Meikisisui.java
> 20250213 Create cf729c_Meikisisui.java

- daily_problems/2025/02/0213/personal_submission/cf237e_lyxxys.cpp
> 20250213_cf237e_lyxxys.cpp

- daily_problems/2025/02/0214/personal_submission/cf939d_Meikisisui.java
20250214 Create cf939d_Meikisisui.java
> 20250214 Create cf939d_Meikisisui.java

- daily_problems/2025/02/0215/personal_submission/cf660c_Meikisisui.java
20250215 Create cf660c_Meikisisui.java
> 20250215 Create cf660c_Meikisisui.java

- daily_problems/2025/02/0218/personal_submission/cf190b_gh123.java
> 20250218 Create cf190b_gh123.java

- daily_problems/2025/02/0218/personal_submission/cf190b_Meikisisui.java
20250218 Create cf190b_Meikisisui.java
> 20250218 Create cf190b_Meikisisui.java

- daily_problems/2025/02/0219/personal_submission/cf540b_Meikisisui.java
20250219 Create cf540b_Meikisisui.java
> 20250219 Create cf540b_Meikisisui.java

- daily_problems/2025/02/0220/personal_submission/cf1227c_Meikisisui.java
20250220 Create cf1227c_Meikisisui.java
> 20250220 Create cf1227c_Meikisisui.java

- daily_problems/2025/02/0222/personal_submission/cf1036b_gh123.java
> 20250222 Create cf1036b_gh123.java

- daily_problems/2025/02/0222/personal_submission/cf1036b_Meikisisui.java
20250222 Create cf1036b_Meikisisui.java
> 20250222 Create cf1036b_Meikisisui.java

- daily_problems/2025/02/0224/personal_submission/cf222c_Meikisisui.java
20250224 Create cf222c_Meikisisui.java
> 20250224 Create cf222c_Meikisisui.java

- daily_problems/2025/02/0224/personal_submission/cf1689d_Meikisisui.java
20250224 Create cf1689d_Meikisisui.java
> 20250224 Create cf1689d_Meikisisui.java

- daily_problems/2025/02/0226/personal_submission/cf374a_Meikisisui.java
20250226 Create cf374a_Meikisisui.java
> 20250226 Create cf374a_Meikisisui.java

- daily_problems/2025/02/0227/personal_submission/cf923a_lazyyangyang.java
20250227 lazyyangyang's submission for CF923A
> cf923a_lazyyangyang.java

- daily_problems/2025/02/0228/personal_submission/cf1468k_Meikisisui.java
20250228 Create cf1468k_Meikisisui.java
> 20250228 Create cf1468k_Meikisisui.java

- daily_problems/2025/03/0301/personal_submission/cf1225e_lyxxys.cpp
> 20250301_cf1225e_lyxxys.cpp

- daily_problems/2025/03/0301/personal_submission/cf1238c_Meikisisui.java
20250301 Create cf1238c_Meikisisui.java
> 20250301 Create cf1238c_Meikisisui.java

- daily_problems/2025/03/0303/personal_submission/cf958f2_Meikisisui.java
20250303 Create cf958f2_Meikisisui.java
> 20250303 Create cf958f2_Meikisisui.java

- daily_problems/2025/03/0304/personal_submission/cf923c_Meikisisui.java
20250304 Create cf923c_Meikisisui.java
> 20250304 Create cf923c_Meikisisui.java

- daily_problems/2025/03/0307/personal_submission/cf1866h_lyxxys.cpp
> 20250307_cf1866h_lyxxys.cpp

- daily_problems/2025/03/0301/personal_submission/cf1238c_kevinwangsus.py
> 20250301 kevinwangsus's submission

- daily_problems/2025/03/0303/personal_submission/cf803d_kevinwangsus.py
- daily_problems/2025/03/0303/personal_submission/cf958f2_kevinwangsus.py
20250303 cf803d
20250303 cf958f2
> 20250303 kevinwangsus's submission

- daily_problems/2025/03/0311/personal_submission/cf123b_guangong789.cpp
- daily_problems/2025/03/0311/personal_submission/cf342c_guangong789.cpp
> 20250311 guangong789's submissions for cf

- daily_problems/2025/03/0313/personal_submission/cf193b_guangong789.cpp
- daily_problems/2025/03/0313/personal_submission/cf980c_guangong789.cpp
> 20250313 guangong789's submissions for cf

- daily_problems/2025/03/0313/personal_submission/cf980c_Meikisisui.java
20250313 Create cf980c_Meikisisui.java
> 20250313 Create cf980c_Meikisisui.java

- daily_problems/2025/03/0314/personal_submission/cf733d_Meikisisui.java
20250314 Create cf733d_Meikisisui.java
> 20250314 Create cf733d_Meikisisui.java

- daily_problems/2025/03/0314/personal_submission/cf733d_guangong789.cpp
> 20250314 guangong789's submission for cf733d

- daily_problems/2025/03/0314/personal_submission/cf733d_dinghc.cpp
> 20250314 dinghc's submission

- daily_problems/2025/03/0315/personal_submission/cf595b_gh123.java
> 20250315 Create cf595b_gh123.java

- daily_problems/2025/03/0315/personal_submission/cf595b_Meikisisui.java
20250315 Create cf595b_Meikisisui.java
> 20250315 Create cf595b_Meikisisui.java

- daily_problems/2025/03/0315/personal_submission/cf595b_guangong789.cpp
> 20250315 guangong789's submission for cf595b

- daily_problems/2025/03/0315/personal_submission/cf595b_dinghc.cpp
> 20250315 dinghc's submission

- daily_problems/2025/03/0317/personal_submission/cf883k_Meikisisui.java
20250316 Create cf883k_Meikisisui.java
> 20250316 Create cf883k_Meikisisui.java

- daily_problems/2025/03/0318/personal_submission/cf1955f_guangong789.cpp
> 20250318 guangong789's submission for cf1955f

- daily_problems/2025/03/0318/personal_submission/cf1955f_Meikisisui.java
20250318 Create cf1955f_Meikisisui.java
> 20250318 Create cf1955f_Meikisisui.java

- daily_problems/2025/03/0319/personal_submission/cf1850h_guangong789.cpp
> 20250319 guangong789's submission for cf1850h

- daily_problems/2025/03/0319/personal_submission/cf1850h_Meikisisui.java
20250319 Create cf1850h_Meikisisui.java
> 20250319 Create cf1850h_Meikisisui.java

- daily_problems/2025/03/0319/personal_submission/cf1850h_dinghc.cpp
> 20250319 dinghc's submission

- daily_problems/2025/03/0320/personal_submission/cf910c_guangong789.cpp
> 20250320 guangong789's submission for cf910c

- daily_problems/2025/03/0320/personal_submission/cf910c_Meikisisui.java
20250320 Create cf910c_Meikisisui.java
> 20250320 Create cf910c_Meikisisui.java

- daily_problems/2025/03/0321/personal_submission/cf214b_Meikisisui.java
20250321 Create cf214b_Meikisisui.java
> 20250321 Create cf214b_Meikisisui.java

- daily_problems/2025/03/0321/personal_submission/cf214b_guangong789.cpp
> 20250321 guangong789's submission for cf214b

- daily_problems/2025/03/0322/personal_submission/cf617c_guangong789.cpp
> 20250322 guangong789's submission for cf617c

- daily_problems/2025/03/0322/personal_submission/cf617c_Meikisisui.java
20250322 Create cf617c_Meikisisui.java
> 20250322 Create cf617c_Meikisisui.java

- daily_problems/2025/03/0322/personal_submission/cf617c_dinghc.cpp
> 20250322 dinghc's submission

- daily_problems/2025/03/0324/personal_submission/cf1089f_guangong789.cpp
- daily_problems/2025/03/0324/personal_submission/cf404c_guangong789.cpp
> 20250324 guangong789's submissions for cf

- daily_problems/2025/03/0324/personal_submission/cf404c_dinghc.cpp
> 20250324 dinghc's submission

- daily_problems/2025/03/0325/personal_submission/cf488b_guangong789.cpp
- daily_problems/2025/03/0325/personal_submission/cf638c_guangong789.cpp
> 20250325 guangong789's submissions for cf

- daily_problems/2025/03/0326/personal_submission/cf718a_guangong789.cpp
> 20250326 guangong789's submission for cf718a

- daily_problems/2025/03/0326/personal_submission/cf718a_dinghc.cpp
> 20250326 dinghc's submission

- daily_problems/2025/03/0327/personal_submission/cf1202b_guangong789.cpp
> 20250327 guangong789's submission for cf1202b

- daily_problems/2025/03/0328/personal_submission/cf930b_guangong789.cpp
> 20250328 guangong789's submission for cf930b

- daily_problems/2025/03/0328/personal_submission/cf930b_dinghc.cpp
> 20250328 dinghc's submission

- daily_problems/2025/03/0329/personal_submission/cf380a_dinghc.cpp
> 20250329 dinghc's submission

- daily_problems/2025/03/0331/personal_submission/cf255d_gh123.java
> 20250331 Create cf255d_gh123.java

- daily_problems/2025/04/0401/personal_submission/cf691c_Meikisisui.java
20250401 Create cf691c_Meikisisui.java
> 20250401 Create cf691c_Meikisisui.java

- daily_problems/2025/04/0401/personal_submission/cf691c_dinghc.cpp
> 20250401 dinghc's submission

- daily_problems/2025/04/0402/personal_submission/cf766c_gh123.java
> 20250402 Create cf766c_gh123.java

- daily_problems/2025/04/0402/personal_submission/cf766c_Meikisisui.java
20250402 Create cf766c_Meikisisui.java
> 20250402 Create cf766c_Meikisisui.java

- daily_problems/2025/04/0402/personal_submission/cf766c_guangong789.cpp
> 20250402 guangong789's submission for cf766c

- daily_problems/2025/04/0402/personal_submission/cf1090k_nhantran0.java
I'm not sure how to reach you for a question so I'll just ask here:
- What's the official close time in term of hour & time zone for 2 daily CF problems after which you no longer allow the submissions to contribute to the streak?
- I assume this also means any submissions for >=2 days ago aren't counted as valid submissions for those days. Am I right?
> 20250402 nhantran0's submission for CF1090K

- daily_problems/2025/04/0403/personal_submission/cf405d_gh123.java
> 20250403 Create cf405d_gh123.java

- daily_problems/2025/04/0403/personal_submission/cf405d_guangong789.cpp
> 20250403 guangong789's submission for cf405d

- daily_problems/2025/04/0403/personal_submission/cf405d_Meikisisui.java
20250403 Create cf405d_Meikisisui.java
> 20250403 Create cf405d_Meikisisui.java

- daily_problems/2025/04/0405/personal_submission/cf715a_guangong789.cpp
> 20250405 guangong789's submission for cf715a

- daily_problems/2025/04/0405/personal_submission/cf1090e_lyxxys.cpp
> 20250407_cf1090e_lyxxys.cpp

- daily_problems/2025/04/0407/personal_submission/cf83b_Meikisisui.java
20250407 Create cf83b_Meikisisui.java
> 20250407 Create cf83b_Meikisisui.java

- daily_problems/2025/04/0407/personal_submission/cf83b_guangong789.cpp
> 20250407 guangong789's submission for cf83b

- daily_problems/2025/04/0407/personal_submission/cf1938c_lyxxys.cpp
> 202504047_cf1938c_lyxxys.cpp

- daily_problems/2025/04/0408/personal_submission/cf727d_Meikisisui.java
20250408 Create cf727d_Meikisisui.java
> 20250408 Create cf727d_Meikisisui.java

- daily_problems/2025/04/0409/personal_submission/cf442a_dinghc.cpp
> 20250409 dinghc's submission

- daily_problems/2025/04/0409/personal_submission/cf442a_guangong789.cpp
> 20250409 guangong789's submission for cf442a

- daily_problems/2025/04/0411/personal_submission/cf272d_gh123.java
> 20250411 Create cf272d_gh123.java

- daily_problems/2025/04/0411/personal_submission/cf272d_dinghc.cpp
> 20250411 dinghc's submission

- daily_problems/2025/04/0412/personal_submission/cf605a_guangong789.cpp
> 20250412 gaungong789's submission for cf605a

- daily_problems/2025/04/0414/personal_submission/cf630m_guangong789.cpp
> 20250414 guangong789's submission for cf630m

- daily_problems/2025/04/0412/personal_submission/cf1089a_lyxxys.cpp
> 20250415_cf1089a_lyxxys.cpp

- daily_problems/2025/04/0415/personal_submission/cf353b_lyxxys.cpp
> 20250415_cf353b_lyxxys.cpp

- daily_problems/2025/04/0415/personal_submission/cf187b_guangong789.cpp
- daily_problems/2025/04/0415/personal_submission/cf353b_guangong789.cpp
> 20250415 guangong789's submission for cf353b

- daily_problems/2025/04/0415/personal_submission/cf187b_dinghc.cpp
> 20250415 dinghc's submission

- daily_problems/2025/04/0416/personal_submission/cf813c_guangong789.cpp
> 20250416 guangong789's submission for cf813c

- daily_problems/2025/04/0417/personal_submission/cf676d_lyxxys.cpp
> 20250417_cf676d_lyxxys.cpp

- daily_problems/2025/04/0417/personal_submission/cf1835a_guangong789.cpp
- daily_problems/2025/04/0418/personal_submission/cf603a_guangong789.cpp
> 20250418 guangong789's submission for cf

- daily_problems/2025/04/0419/personal_submission/cf317a_guangong789.cpp
> 20250419 guangong789's submission for cf317a

- daily_problems/2025/04/0421/personal_submission/cf1277d_guangong789.cpp
> 20250421 guangong789's submission for cf1277d

- daily_problems/2025/04/0421/personal_submission/cf87b_dinghc.cpp
> 20250421 dinghc's submission

- daily_problems/2025/04/0419/personal_submission/cf200a_lyxxys.cpp
> 20250422_cf200a_lyxxys.cpp

- daily_problems/2025/04/0422/personal_submission/cf847c_guangong789.cpp
> 20250421 guangong789's submission for cf847c

- daily_problems/2025/04/0422/personal_submission/cf490d_dinghc.cpp
- daily_problems/2025/04/0422/personal_submission/cf847c_dinghc.cpp
> 20250422 dinghc's submission

- daily_problems/2025/04/0423/personal_submission/cf1092c_guangong789.cpp
- daily_problems/2025/04/0423/personal_submission/cf818c_guangong789.cpp
> 20250423 guangong789's submission

- daily_problems/2025/04/0423/personal_submission/cf818c_Yfanx.cpp
20250423 Yfanx's submissions of CF818C
> 20250423 Yfanx's submissions of CF818C

- daily_problems/2025/04/0423/personal_submission/cf1092c_Yfanx.cpp
20250423 Yfanx's submission for CF1092C
> 20250423 Yfanx's submission for CF1092C

- daily_problems/2025/04/0423/personal_submission/cf1092c_dinghc.cpp
> 20250423 dinghc's submission

- daily_problems/2025/04/0424/personal_submission/cf1468d_dinghc.cpp
> 20250424 dinghc's submission

- daily_problems/2025/04/0425/personal_submission/cf793b_guangong789.cpp
> 20250425 guangong789's submission for cf793b

- daily_problems/2025/04/0426/personal_submission/cf616c_dinghc.cpp
> 20250426 dinghc's submission

- daily_problems/2025/04/0426/personal_submission/cf616c_guangong789.cpp
> 20250426 guangong789's submission for cf616c

- daily_problems/2025/04/0428/personal_submission/cf845d_dinghc.cpp
> 20250428 dinghc's submission

- daily_problems/2025/04/0428/personal_submission/cf845d_nhantran0.cpp
- daily_problems/2025/04/0428/personal_submission/cf845d_nhantran0.java
Edu Round 27 (1866) D. Driving Test
> 20250428 submissions for CF845D

- daily_problems/2025/04/0429/personal_submission/cf690e1_Yfanx_cpp
20250429 Yfanx's submission for CF690E1
> 20250429 Yfanx's submission for CF690E1

- daily_problems/2025/04/0429/personal_submission/cf690e1_nhantran0.cpp
- daily_problems/2025/04/0429/personal_submission/cf690e1_nhantran0.java
> 20250429 submissions for CF690E1

- daily_problems/2025/04/0429/personal_submission/cf690e1_lyxxys.cpp
> 20250429_cf690e1_lyxxys.cpp

- daily_problems/2025/04/0429/personal_submission/cf367b_dinghc.cpp
> 20250429 dinghc's submission

- daily_problems/2025/04/0429/personal_submission/cf367b_nhantran0.cpp
- daily_problems/2025/04/0429/personal_submission/cf367b_nhantran0.java
Codeforces Round 215 (Div. 1): (2026) B. Sereja ans Anagrams
> 20250429 submissions for CF367B

- daily_problems/2025/04/0428/personal_submission/cf845d_firefly.cs
- daily_problems/2025/04/0429/personal_submission/cf367b_firefly.cs
- daily_problems/2025/04/0429/personal_submission/cf690e1_firefly.cs
- daily_problems/2025/04/0430/personal_submission/cf2073j_firefly.cs
- daily_problems/2025/04/0430/personal_submission/cf269b_firefly.cs
0428:
https://codeforces.com/problemset/submission/845/317837060
0429:
https://codeforces.com/problemset/submission/690/317826471
https://codeforces.com/problemset/submission/367/317834617
0430:
https://codeforces.com/problemset/submission/269/317822085
https://codeforces.com/problemset/submission/2073/317824782
> -firefly- 202504

- daily_problems/2025/04/0430/personal_submission/cf269b_dinghc.cpp
- daily_problems/2025/05/0501/personal_submission/cf617d_dinghc.cpp
> 20250501 dinghc's submission

- daily_problems/2025/05/0501/personal_submission/cf617d_firefly.cs
- daily_problems/2025/05/0502/personal_submission/cf375b_firefly.cs
- daily_problems/2025/05/0502/personal_submission/cf631b_firefly.cs
0501:
https://codeforces.com/problemset/submission/617/318123148
0502:
https://codeforces.com/problemset/submission/375/318117550
https://codeforces.com/problemset/submission/631/318121464
> firefly 20250502

- daily_problems/2025/05/0507/personal_submission/cf245c_dinghc.cpp
> 20250507 dinghc's submission

- daily_problems/2025/05/0508/personal_submission/cf662d_lyxxys.cpp
> 20250508_cf662d_lyxxys.cpp

- daily_problems/2025/05/0508/personal_submission/cf605b_dinghc.cpp
> 20250508 dinghc's submission

- daily_problems/2025/05/0509/personal_submission/cf877c_Meikisisui.java
20250509 Create cf877c_Meikisisui.java
> 20250509 Create cf877c_Meikisisui.java

- daily_problems/2025/05/0510/personal_submission/cf689b_gh123.java
> 20250510 Create cf689b_gh123.java

- daily_problems/2025/05/0510/personal_submission/cf689b_Meikisisui.java
20250510 Create cf689b_Meikisisui.java
> 20250510 Create cf689b_Meikisisui.java

- daily_problems/2025/05/0513/personal_submission/cf67b_Meikisisui.java
20250513 Create cf67b_Meikisisui.java
> 20250513 Create cf67b_Meikisisui.java

- daily_problems/2025/05/0513/personal_submission/cf67b_dinghc.cpp
> 20250513 dinghc's submission

- daily_problems/2025/05/0513/personal_submission/cf208c_dinghc.cpp
- daily_problems/2025/05/0514/personal_submission/cf294b_dinghc.cpp
> 20250514 dinghc's submission

- daily_problems/2025/05/0515/personal_submission/cf327c_dinghc.cpp
> 20250515 dinghc's submission

- daily_problems/2025/05/0516/personal_submission/cf780c_Meikisisui.java
20250516 Create cf780c_Meikisisui.java
> 20250516 Create cf780c_Meikisisui.java

- daily_problems/2025/05/0516/personal_submission/cf780c_dinghc.cpp
> 20250516 dinghc's submission

- daily_problems/2025/05/0517/personal_submission/cf932c_dinghc.cpp
> 20250517 dinghc's submission

- daily_problems/2025/05/0517/personal_submission/cf932c_Meikisisui.java
20250518 Create cf932c_Meikisisui.java
> 20250518 Create cf932c_Meikisisui.java

- daily_problems/2025/05/0519/personal_submission/cf1915g_dinghc.cpp
> 20250519 dinghc's submission

- daily_problems/2025/05/0520/personal_submission/cf261b_lyxxys.cpp
> 20250520_cf261b_lyxxys.cpp

- daily_problems/2025/05/0520/personal_submission/cf141c_lyxxys.cpp
> 20250520_cf141c_lyxxys.cpp

- daily_problems/2025/05/0520/personal_submission/cf141c_dinghc.cpp
> 20250520 dinghc's submission

- daily_problems/2025/05/0521/personal_submission/cf275b_tiny_fish.cpp
20250521 added sol cf275b_tiny_fish.cpp
> 20250521 added sol cf275b_tiny_fish.cpp

- daily_problems/2025/05/0522/personal_submission/cf685a_dinghc.cpp
> 20250522 dinghc's submission

- daily_problems/2025/05/0522/personal_submission/cf685a_Meikisisui.java
20250522 Create cf685a_Meikisisui.java
> 20250522 Create cf685a_Meikisisui.java

- daily_problems/2025/05/0522/personal_submission/cf685a_hsqgrjs.py
```cpp
#include <bits/stdc++.h>
using namespace std;
using i64 = long long;
using u64 = unsigned long long;
using i128 = __int128_t;
i64 t1 = 0;
void solve() {
i64 n, m;
std::cin >> n >> m;
if(n > 823542 || m > 823542) {
std::cout << 0 << "\n";
return;
}
std::string s1, s2;
--n, --m;
if(n == 0) {
s1 = "0";
} else {
int x = n;
while(x) {
s1 += '0';
x /= 7;
}
}
if(m == 0) {
s2 = "0";
} else {
int x = m;
while(x) {
s2 += '0';
x /= 7;
}
}
if(s1.size() + s2.size() > 7) {
std::cout << 0 << "\n";
return;
}
i64 ans = 0;
for(int i = 0; i <= n; i++) {
for(int j= 0; j <= m; j++) {
std::string s11 = s1, s22 = s2;
i64 t1 = i;
int k = 0;
while(t1) {
s11[k++] = t1 % 7 + '0';
t1 /= 7; 
}
k = 0;
t1 = j;
while(t1) {
s22[k++] = t1 % 7 + '0';
t1 /= 7;
}  
bool ok = 1;
for(int c = 0; c < 7; c++) { …
```
> 20250522 Create cf685a_hsqgrjs.cpp

- daily_problems/2025/05/0522/personal_submission/cf685a_hsqgrjs.py
#include <bits/stdc++.h>
using namespace std;
using i64 = long long;
using u64 = unsigned long long;
using i128 = __int128_t;
i64 t1 = 0;
void solve() {
i64 n, m;
std::cin >> n >> m;
if(n > 823542 || m > 823542) {
std::cout << 0 << "\n";
return;
}
std::string s1, s2;
--n, --m;
if(n == 0) {
s1 = "0";
} else {
int x = n;
while(x) {
s1 += '0';
x /= 7;
}
}
if(m == 0) {
s2 = "0";
} else {
int x = m;
while(x) {
s2 += '0';
x /= 7;
}
}
if(s1.size() + s2.size() > 7) {
std::cout << 0 << "\n";
return;
}
i64 ans = 0;
for(int i = 0; i <= n; i++) {
for(int j= 0; j <= m; j++) {
std::string s11 = s1, s22 = s2;
i64 t1 = i;
int k = 0;
while(t1) {
s11[k++] = t1 % 7 + '0';
t1 /= 7; 
}
k = 0;
t1 = j;
while(t1) {
s22[k++] = t1 % 7 + '0';
t1 /= 7;
}  
bool ok = 1;
for(int c = 0; c < 7; c++) { …
> 20250522 Create cf685a_hsqgrjs.py

- daily_problems/2025/05/0523/personal_submission/cf818b_dinghc.cpp
> 20250523 dinghc's submission

- daily_problems/2025/05/0524/personal_submission/cf373b_dinghc.cpp
> 20250524 dinghc's submission

- daily_problems/2025/05/0527/personal_submission/cf73c_dinghc.cpp
> 20250527 dinghc's submission

- daily_problems/2025/05/0528/personal_submission/cf216d_dinghc.cpp
> 20250528 dinghc's submission

- daily_problems/2025/05/0530/personal_submission/cf440b_dinghc.cpp
> 20250530 dinghc's submission

- daily_problems/2025/06/0603/personal_submission/cf140c_gh123.java
> 20250603 Create cf140c_gh123.java

- daily_problems/2025/06/0605/personal_submission/cf815a_dinghc.cpp
> 20250605 dinghc's submission

- daily_problems/2025/06/0611/personal_submission/cf303b_gh123.java
> 20250611 Create cf303b_gh123.java

- daily_problems/2025/06/0614/personal_submission/cf1006e_dinghc.cpp
> 20250614 dinghc's submission

- daily_problems/2025/06/0619/personal_submission/cf321a_Meikisisui.java
20250619 Create cf321a_Meikisisui.java
> 20250619 Create cf321a_Meikisisui.java

- daily_problems/2025/06/0620/personal_submission/cf898e_Meikisisui.java
20250620 Create cf898e_Meikisisui.java
> 20250620 Create cf898e_Meikisisui.java

- daily_problems/2025/06/0621/personal_submission/cf618c_Meikisisui.java
20250621 Create cf618c_Meikisisui.java
> 20250621 Create cf618c_Meikisisui.java

- daily_problems/2025/06/0621/personal_submission/cf618c_dinghc.cpp
> 20250621 dinghc's submission

- daily_problems/2025/06/0624/personal_submission/cf58c_KaosPower.py
20250624 Create cf58c_KaosPower.py
> 20250624 Create cf58c_KaosPower.py

- daily_problems/2025/06/0627/personal_submission/cf1225c_KaosPower.cpp
20250627 Create cf1225c_KaosPower.cpp
> 20250627 Create cf1225c_KaosPower.cpp

- daily_problems/2025/06/0628/personal_submission/cf741a_Meikisisui.java
20250628 Create cf741a_Meikisisui.java
> 20250628 Create cf741a_Meikisisui.java

- daily_problems/2025/06/0628/personal_submission/cf741a_dinghc.cpp
> 20250628 dinghc's submission

- daily_problems/2025/06/0630/personal_submission/cf30c_KaosPower.py
20250630 Create cf30c_KaosPower.py
> 20250630 Create cf30c_KaosPower.py

- daily_problems/2025/07/0701/personal_submission/cf44d_Meikisisui.java
20250701 Create cf44d_Meikisisui.java
> 20250701 Create cf44d_Meikisisui.java

- daily_problems/2025/07/0701/personal_submission/cf44d_KaosPower.cpp
20250701 Create cf44d_KaosPower.cpp
> 20250701 Create cf44d_KaosPower.cpp

- daily_problems/2025/07/0702/personal_submission/cf1810d_Meikisisui.java
20250702 Create cf1810d_Meikisisui.java
> 20250702 Create cf1810d_Meikisisui.java

- daily_problems/2025/07/0703/personal_submission/cf625a_KaosPower.py
20250703 Create cf625a_KaosPower.py
> 20250703 Create cf625a_KaosPower.py

- daily_problems/2025/07/0704/personal_submission/cf234g_Meikisisui.java
20250704 Create cf234g_Meikisisui.java
> 20250704 Create cf234g_Meikisisui.java

- daily_problems/2025/07/0704/personal_submission/cf234g_KaosPower.cpp
20250704 Create cf234g_KaosPower.cpp
> 20250704 Create cf234g_KaosPower.cpp

- daily_problems/2025/07/0705/personal_submission/cf1833e_dinghc.cpp
> 20250705 dinghc's submission

- daily_problems/2025/07/0707/personal_submission/cf49d_Meikisisui.java
20250707 Create cf49d_Meikisisui.java
> 20250707 Create cf49d_Meikisisui.java

- daily_problems/2025/07/0707/personal_submission/cf49d_gh123.java
> 20250707 Create cf49d_gh123.java

- daily_problems/2025/07/0707/personal_submission/cf49d_KaosPower.py
20250707 Create cf49d_KaosPower.py
> 20250707 Create cf49d_KaosPower.py

- daily_problems/2025/07/0707/personal_submission/cf49d_dinghc.cpp
> 20250707 dinghc's submission

- daily_problems/2025/07/0708/personal_submission/cf690d2_Meikisisui.java
20250708 Create cf690d2_Meikisisui.java
> 20250708 Create cf690d2_Meikisisui.java

- daily_problems/2025/07/0708/personal_submission/cf690d2_KaosPower.cpp
20250708 Create cf690d2_KaosPower.cpp
> 20250708 Create cf690d2_KaosPower.cpp

- daily_problems/2025/07/0709/personal_submission/cf260c_gh123.java
> 20250709 Create cf260c_gh123.java

- daily_problems/2025/07/0709/personal_submission/cf260c_KaosPower.cpp
20250709 Create cf260c_KaosPower.cpp
> 20250709 Create cf260c_KaosPower.cpp

- daily_problems/2025/07/0710/personal_submission/cf183b_KaosPower.cpp
20250710 Create cf183b_KaosPower.cpp
> 20250710 Create cf183b_KaosPower.cpp

- daily_problems/2025/07/0711/personal_submission/cf316b2_KaosPower.cpp
20250711 Create cf316b2_KaosPower.cpp
> 20250711 Create cf316b2_KaosPower.cpp

- daily_problems/2025/07/0712/personal_submission/cf305c_gh123.java
> 20250712 Create cf305c_gh123.java

- daily_problems/2025/07/0712/personal_submission/cf305c_KaosPower.cpp
20250712 Create cf305c_KaosPower.cpp
> 20250712 Create cf305c_KaosPower.cpp

- daily_problems/2025/07/0712/personal_submission/cf305c_dinghc.cpp
> 20250712 dinghc's submission

- daily_problems/2025/07/0714/personal_submission/cf45j_gh123.java
> 20250714 Create cf45j_gh123.java

- daily_problems/2025/07/0714/personal_submission/cf45j_KaosPower.cpp
20250714 Create cf45j_KaosPower.cpp
> 20250714 Create cf45j_KaosPower.cpp

- daily_problems/2025/07/0715/personal_submission/cf2045m_KaosPower.cpp
20250715 Create cf2045m_KaosPower.cpp
> 20250715 Create cf2045m_KaosPower.cpp

- daily_problems/2025/07/0716/personal_submission/cf223a_Meikisisui.java
20250716 Create cf223a_Meikisisui.java
> 20250716 Create cf223a_Meikisisui.java

- daily_problems/2025/07/0717/personal_submission/cf1931f_KaosPower.cpp
20250717 Create cf1931f_KaosPower.cpp
> 20250717 Create cf1931f_KaosPower.cpp

- daily_problems/2025/07/0719/personal_submission/cf493c_gh123.java
//
村长熬夜有点厉害啊，不然每日一题也行的，或者2天一题。
//
> 20250719 Create cf493c_gh123.java

- daily_problems/2025/07/0719/personal_submission/cf493c_Meikisisui.java
20250719 Create cf493c_Meikisisui.java
> 20250719 Create cf493c_Meikisisui.java

- daily_problems/2025/07/0722/personal_submission/cf370c_KaosPower.cpp
20250722 Create cf370c_KaosPower.cpp
> 20250722 Create cf370c_KaosPower.cpp

- daily_problems/2025/07/0722/personal_submission/cf370c_Meikisisui.java
20250722 Create cf370c_Meikisisui.java
> 20250722 Create cf370c_Meikisisui.java

- daily_problems/2025/07/0724/personal_submission/cf847f_KaosPower.cpp
20250724 Create cf847f_KaosPower.cpp
> 20250724 Create cf847f_KaosPower.cpp

- daily_problems/2025/07/0725/personal_submission/cf101d_KaosPower.cpp
20250725 Create cf101d_KaosPower.cpp
> 20250725 Create cf101d_KaosPower.cpp

- daily_problems/2025/07/0725/personal_submission/cf209a_dinghc.cpp
- daily_problems/2025/07/0726/personal_submission/cf825c_dinghc.cpp
> 20250726 dinghc's submission

- daily_problems/2025/07/0726/personal_submission/cf825c_KaosPower.cpp
20250726 Create cf825c_KaosPower.cpp
> 20250726 Create cf825c_KaosPower.cpp

- daily_problems/2025/07/0726/personal_submission/cf825c_Meikisisui.java
20250726 Create cf825c_Meikisisui.java
> 20250726 Create cf825c_Meikisisui.java

- daily_problems/2025/07/0728/personal_submission/cf319b_Meikisisui.java
20250728 Create cf319b_Meikisisui.java
> 20250728 Create cf319b_Meikisisui.java

- daily_problems/2025/07/0728/personal_submission/cf585a_KaosPower.cpp
20250728 Create cf585a_KaosPower.cpp
> 20250728 Create cf585a_KaosPower.cpp

- daily_problems/2025/07/0729/personal_submission/cf420b_KaosPower.cpp
20250729 Create cf420b_KaosPower.cpp
> 20250729 Create cf420b_KaosPower.cpp

- daily_problems/2025/07/0730/personal_submission/cf471c_dinghc.cpp
> 20250730 dinghc's submission

- daily_problems/2025/07/0731/personal_submission/cf1015e1_KaosPower.py
20250731 Create cf1015e1_KaosPower.py
> 20250731 Create cf1015e1_KaosPower.py

- daily_problems/2025/08/0801/personal_submission/cf163a_Meikisisui.java
20250801 Create cf163a_Meikisisui.java
> 20250801 Create cf163a_Meikisisui.java

- daily_problems/2025/08/0801/personal_submission/cf163a_dinghc.cpp
> 20250801 dinghc's submission

- daily_problems/2025/08/0802/personal_submission/cf154b_dinghc.cpp
> 20250802 dinghc's submission

- daily_problems/2025/08/0802/personal_submission/cf154b_Meikisisui.java
20250802 Create cf154b_Meikisisui.java
> 20250802 Create cf154b_Meikisisui.java

- daily_problems/2025/08/0804/personal_submission/cf33c_Meikisisui.java
20250804 Create cf33c_Meikisisui.java
> 20250804 Create cf33c_Meikisisui.java

- daily_problems/2025/08/0804/personal_submission/cf33c_KaosPower.cpp
20250804 Create cf33c_KaosPower.cpp
> 20250804 Create cf33c_KaosPower.cpp

- daily_problems/2025/08/0805/personal_submission/cf274b_KaosPower.cpp
20250805 Create cf274b_KaosPower.cpp
> 20250805 Create cf274b_KaosPower.cpp

- daily_problems/2025/08/0806/personal_submission/cf269a_KaosPower.cpp
20250806 Create cf269a_KaosPower.cpp
> 20250806 Create cf269a_KaosPower.cpp

- daily_problems/2025/08/0807/personal_submission/cf131e_KaosPower.cpp
20250807 Create cf131e_KaosPower.cpp
> 20250807 Create cf131e_KaosPower.cpp

- daily_problems/2025/08/0808/personal_submission/cf856a_Meikisisui.java
20250808 Create cf856a_Meikisisui.java
> 20250808 Create cf856a_Meikisisui.java

- daily_problems/2025/08/0809/personal_submission/cf246c_KaosPower.cpp
20250809 Create cf246c_KaosPower.cpp
> 20250809 Create cf246c_KaosPower.cpp

- daily_problems/2025/08/0809/personal_submission/cf246c_dinghc.cpp
> 20250809 dinghc's submission

- daily_problems/2025/08/0811/personal_submission/cf652c_Meikisisui.java
20250811 Create cf652c_Meikisisui.java
> 20250811 Create cf652c_Meikisisui.java

- daily_problems/2025/08/0811/personal_submission/cf652c_KaosPower.cpp
20250811 Create cf652c_KaosPower.cpp
> 20250811 Create cf652c_KaosPower.cpp

- daily_problems/2025/08/0812/personal_submission/cf991e_KaosPower.cpp
20250812 Create cf991e_KaosPower.cpp
> 20250812 Create cf991e_KaosPower.cpp

- daily_problems/2025/08/0813/personal_submission/cf1006d_KaosPower.cpp
20250813 Create cf1006d_KaosPower.cpp
> 20250813 Create cf1006d_KaosPower.cpp

- daily_problems/2025/08/0814/personal_submission/cf148c_Meikisisui.java
20250814 Create cf148c_Meikisisui.java
> 20250814 Create cf148c_Meikisisui.java

- daily_problems/2025/08/0814/personal_submission/cf148c_KaosPower.cpp
20250814 Create cf148c_KaosPower.cpp
> 20250814 Create cf148c_KaosPower.cpp

- daily_problems/2025/08/0815/personal_submission/cf283a_dinghc.cpp
> 20250815 dinghc's submission

- daily_problems/2025/08/0816/personal_submission/cf518c_KaosPower.cpp
20250816 Create cf518c_KaosPower.cpp
> 20250816 Create cf518c_KaosPower.cpp

- daily_problems/2025/08/0816/personal_submission/cf518c_Meikisisui.java
20250816 Create cf518c_Meikisisui.java
> 20250816 Create cf518c_Meikisisui.java

- daily_problems/2025/08/0819/personal_submission/cf1941f_Meikisisui.java
20250819 Create cf1941f_Meikisisui.java
> 20250819 Create cf1941f_Meikisisui.java

- daily_problems/2025/08/0819/personal_submission/cf1941f_lyxxys.java
> 20250820_cf1941f_lyxxys.java

- daily_problems/2025/08/0820/personal_submission/cf160c_Meikisisui.java
20250820 Create cf160c_Meikisisui.java
> 20250820 Create cf160c_Meikisisui.java

- daily_problems/2025/08/0820/personal_submission/cf160c_dinghc.cpp
> 20250820 dinghc's submission

- daily_problems/2025/08/0821/personal_submission/cf203d_KaosPower.cpp
20250821 Create cf203d_KaosPower.cpp
> 20250821 Create cf203d_KaosPower.cpp

- daily_problems/2025/08/0825/personal_submission/cf15b_Meikisisui.java
20250825 Create cf15b_Meikisisui.java
> 20250825 Create cf15b_Meikisisui.java

- daily_problems/2025/08/0825/personal_submission/cf15b_KaosPower.cpp
20250825 Create cf15b_KaosPower.cpp
> 20250825 Create cf15b_KaosPower.cpp

- daily_problems/2025/08/0826/personal_submission/cf2071d1_Meikisisui.java
20250826 Create cf2071d1_Meikisisui.java
> 20250826 Create cf2071d1_Meikisisui.java

- daily_problems/2025/08/0828/personal_submission/cf1118c_KaosPower.cpp
20250828 Create cf1118c_KaosPower.cpp
> 20250828 Create cf1118c_KaosPower.cpp

- daily_problems/2025/08/0828/personal_submission/cf1118c_Meikisisui.java
20250828 Create cf1118c_Meikisisui.java
> 20250828 Create cf1118c_Meikisisui.java

- daily_problems/2025/09/0901/personal_submission/cf778b_KaosPower.cpp
20250901 Create cf778b_KaosPower.cpp
> 20250901 Create cf778b_KaosPower.cpp

- daily_problems/2025/09/0902/personal_submission/cf145b_KaosPower.cpp
20250902 Create cf145b_KaosPower.cpp
> 20250902 Create cf145b_KaosPower.cpp

- daily_problems/2025/09/0901/personal_submission/cf778b_lyxxys.java
> 20250902_cf778b_lyxxys.java

- daily_problems/2025/09/0901/personal_submission/cf63d_lyxxys.java
> 20250903_cf63d_lyxxys.java

- daily_problems/2025/09/0904/personal_submission/cf81c_KaosPower.cpp
20250904 Create cf81c_KaosPower.cpp
> 20250904 Create cf81c_KaosPower.cpp

- daily_problems/2025/09/0908/personal_submission/cf670e_Meikisisui.java
20250908 Create cf670e_Meikisisui.java
> 20250908 Create cf670e_Meikisisui.java

- daily_problems/2025/09/0908/personal_submission/cf670e_lyxxys.java
> 20250908_cf670e_lyxxys.java

- daily_problems/2025/09/0915/personal_submission/cf102861i_poisonous-sheep.cpp
> 20250915 poisonous-sheep's submission

- daily_problems/2025/09/0917/personal_submission/cf105562_poisonous-sheep.cpp
> 20250917 poisonous-sheep's submission

- daily_problems/2025/09/0918/personal_submission/cf104772d_poisonous-sheep.cpp
> 20250918 poisonous-sheep's submission

- daily_problems/2025/09/0919/personal_submission/cf104059j_dinghc.cpp
- daily_problems/2025/09/0920/personal_submission/cf105819d_dinghc.cpp
> 20250920 dinghc's submission

- daily_problems/2025/09/0924/personal_submission/cf105552d_Meikisisui.java
20250924 Create cf105552d_Meikisisui.java
> 20250924 Create cf105552d_Meikisisui.java

- daily_problems/2025/09/0924/personal_submission/cf105552d_dinghc.cpp
> 20250924 dinghc's submission

- daily_problems/2025/09/0926/personal_submission/cf106042d_Meikisisui.java
20250926 Create cf106042d_Meikisisui.java
> 20250926 Create cf106042d_Meikisisui.java

- daily_problems/2025/09/0926/personal_submission/cf106042d_dinghc.cpp
> 20250926 dinghc's submission

- daily_problems/2025/09/0927/personal_submission/cf106032j_dinghc.cpp
> 20250927 dinghc's submission

- daily_problems/2025/09/0927/personal_submission/cf106032j_Meikisisui.java
20250927 Create cf106032j_Meikisisui.java
> 20250927 Create cf106032j_Meikisisui.java

- daily_problems/2025/10/1001/personal_submission/cf105833k_gh123.java
//代码几乎完全一样，但是会超时，卡在test24了，不知道哪里还要优化。村长可以不merge的。
> 20251001 Create cf105833k_gh123.java

- daily_problems/2025/10/1002/personal_submission/cf105271b_gh123.java
> 2025 1002 Create cf105271b_gh123.java

- daily_problems/2025/10/1006/personal_submission/cf105053d_kaospower.py
20251006 Create cf105053d_kaospower.py
> 20251006 Create cf105053d_kaospower.py
